CREATE FUNCTION [dbo].[fnx_Numbers]
(@max AS INT)
   RETURNS TABLE AS RETURN
WITH
C0 AS(SELECT 0 AS const UNION ALL SELECT 0),
C1 AS(SELECT 0 AS const FROM C0 AS A, C0 AS B),
C2 AS(SELECT 0 AS const FROM C1 AS A, C1 AS B),
C3 AS(SELECT 0 AS const FROM C2 AS A, C2 AS B),
C4 AS(SELECT 0 AS const FROM C3 AS A, C3 AS B),
C5 AS(SELECT 0 AS const FROM C4 AS A, C4 AS B),
C6 AS(SELECT 0 AS const FROM C5 AS A, C5 AS B)
SELECT TOP(@max) ROW_NUMBER()
   OVER(ORDER BY const) AS n
FROM C6;