// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.Apprenticeships.Web.Candidate.AcceptanceTests.Features.ApprenticeshipApplication
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Apply for an apprenticeship vacancy")]
    public partial class ApplyForAnApprenticeshipVacancyFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ApplyForApprenticeship.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Apply for an apprenticeship vacancy", "\tAs a candidate\r\n\tI want to submit apprenticeship applications \r\n\tso that it can " +
                    "be reviewed by a Vacancy Manager", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line 7
 testRunner.Given("I navigated to the ApprenticeshipSearchPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
 testRunner.And("I am logged out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.And("I navigated to the ApprenticeshipSearchPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.Then("I am on the ApprenticeshipSearchPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("As a candidate I want to save my apprenticeship application as a draft and be abl" +
            "e to resume")]
        [NUnit.Framework.CategoryAttribute("US461")]
        [NUnit.Framework.CategoryAttribute("US154")]
        [NUnit.Framework.CategoryAttribute("US458")]
        [NUnit.Framework.CategoryAttribute("US464")]
        public virtual void AsACandidateIWantToSaveMyApprenticeshipApplicationAsADraftAndBeAbleToResume()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("As a candidate I want to save my apprenticeship application as a draft and be abl" +
                    "e to resume", new string[] {
                        "US461",
                        "US154",
                        "US458",
                        "US464"});
#line 13
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 14
 testRunner.Given("I have registered a new candidate", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 15
 testRunner.When("I select the \"first\" apprenticeship vacancy in location \"N7 8LS\" that can apply b" +
                    "y this website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
 testRunner.Then("I am on the ApprenticeshipDetailsPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 17
 testRunner.When("I choose ApplyButton", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 18
 testRunner.Then("I am on the ApprenticeshipApplicationPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table1.AddRow(new string[] {
                        "EducationNameOfSchool",
                        "SchoolName"});
            table1.AddRow(new string[] {
                        "EducationFromYear",
                        "2010"});
            table1.AddRow(new string[] {
                        "EducationToYear",
                        "2012"});
            table1.AddRow(new string[] {
                        "WhatAreYourStrengths",
                        "My strengths"});
            table1.AddRow(new string[] {
                        "WhatCanYouImprove",
                        "What can I improve"});
            table1.AddRow(new string[] {
                        "HobbiesAndInterests",
                        "Hobbies and interests"});
#line 19
 testRunner.When("I enter data", ((string)(null)), table1, "When ");
#line 27
 testRunner.And("I choose SaveButton", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
 testRunner.Then("I wait to see ApplicationSavedMessage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Rule",
                        "Value"});
            table2.AddRow(new string[] {
                        "ApplicationSavedMessage",
                        "Ends With",
                        "my applications"});
#line 29
 testRunner.And("I see", ((string)(null)), table2, "And ");
#line 32
 testRunner.When("I choose MyApplicationsLink", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 33
 testRunner.Then("I am on the MyApplicationsPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Rule",
                        "Value"});
            table3.AddRow(new string[] {
                        "DraftApplicationsCount",
                        "Equals",
                        "1"});
#line 34
 testRunner.And("I see", ((string)(null)), table3, "And ");
#line 37
 testRunner.When("I choose ResumeLink", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 38
 testRunner.Then("I am on the ApprenticeshipApplicationPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Rule",
                        "Value"});
            table4.AddRow(new string[] {
                        "ApplicationSavedMessage",
                        "Ends With",
                        "my applications"});
            table4.AddRow(new string[] {
                        "EducationNameOfSchool",
                        "Equals",
                        "SchoolName"});
            table4.AddRow(new string[] {
                        "EducationFromYear",
                        "Equals",
                        "2010"});
            table4.AddRow(new string[] {
                        "EducationToYear",
                        "Equals",
                        "2012"});
            table4.AddRow(new string[] {
                        "WhatAreYourStrengths",
                        "Equals",
                        "My strengths"});
            table4.AddRow(new string[] {
                        "WhatCanYouImprove",
                        "Equals",
                        "What can I improve"});
            table4.AddRow(new string[] {
                        "HobbiesAndInterests",
                        "Equals",
                        "Hobbies and interests"});
#line 39
 testRunner.And("I see", ((string)(null)), table4, "And ");
#line 48
 testRunner.When("I choose MyApplicationsLink", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 49
 testRunner.Then("I am on the MyApplicationsPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("As a candidate I want to enter my qualifications and work experience in an appren" +
            "ticeship application")]
        [NUnit.Framework.CategoryAttribute("US461")]
        [NUnit.Framework.CategoryAttribute("US362")]
        [NUnit.Framework.CategoryAttribute("US365")]
        [NUnit.Framework.CategoryAttribute("US154")]
        [NUnit.Framework.CategoryAttribute("US463")]
        [NUnit.Framework.CategoryAttribute("US352")]
        [NUnit.Framework.CategoryAttribute("US354")]
        [NUnit.Framework.CategoryAttribute("PrimaryTransaction")]
        public virtual void AsACandidateIWantToEnterMyQualificationsAndWorkExperienceInAnApprenticeshipApplication()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("As a candidate I want to enter my qualifications and work experience in an appren" +
                    "ticeship application", new string[] {
                        "US461",
                        "US362",
                        "US365",
                        "US154",
                        "US463",
                        "US352",
                        "US354",
                        "PrimaryTransaction"});
#line 52
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 53
 testRunner.Given("I have registered a new candidate", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 54
 testRunner.When("I select the \"first\" apprenticeship vacancy in location \"N7 8LS\" that can apply b" +
                    "y this website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 55
 testRunner.Then("I am on the ApprenticeshipDetailsPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 56
 testRunner.When("I choose ApplyButton", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 57
 testRunner.Then("I am on the ApprenticeshipApplicationPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 60
 testRunner.When("I choose QualificationsYes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 61
 testRunner.And("I choose SaveQualification", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Rule",
                        "Value"});
            table5.AddRow(new string[] {
                        "QualificationsValidationErrorsCount",
                        "Equals",
                        "4"});
#line 62
 testRunner.Then("I see", ((string)(null)), table5, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Rule",
                        "Value"});
            table6.AddRow(new string[] {
                        "Text",
                        "Equals",
                        "GCSE"});
#line 65
 testRunner.When("I am on QualificationTypeDropdown list item matching criteria", ((string)(null)), table6, "When ");
#line 68
 testRunner.And("I choose WrappedElement", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 69
 testRunner.And("I am on the ApprenticeshipApplicationPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table7.AddRow(new string[] {
                        "SubjectYear",
                        "2012"});
            table7.AddRow(new string[] {
                        "SubjectName",
                        "SubjectName"});
            table7.AddRow(new string[] {
                        "SubjectGrade",
                        "SubjectGrade"});
#line 70
 testRunner.When("I enter data", ((string)(null)), table7, "When ");
#line 75
 testRunner.And("I am on the ApprenticeshipApplicationPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 76
 testRunner.And("I choose SaveQualification", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 78
 testRunner.And("I choose SaveQualification", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 79
 testRunner.And("I wait for 30 seconds to see QualificationsSummary", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Rule",
                        "Value"});
            table8.AddRow(new string[] {
                        "QualificationsSummaryCount",
                        "Equals",
                        "1"});
#line 80
 testRunner.Then("I see", ((string)(null)), table8, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Rule",
                        "Value"});
            table9.AddRow(new string[] {
                        "Subject",
                        "Equals",
                        "SubjectName"});
            table9.AddRow(new string[] {
                        "Year",
                        "Equals",
                        "2012"});
            table9.AddRow(new string[] {
                        "Grade",
                        "Equals",
                        "SubjectGrade"});
#line 83
 testRunner.And("I am on QualificationsSummaryItems list item matching criteria", ((string)(null)), table9, "And ");
#line 88
 testRunner.When("I choose RemoveQualificationLink", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 89
 testRunner.And("I am on the ApprenticeshipApplicationPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Rule",
                        "Value"});
            table10.AddRow(new string[] {
                        "QualificationsSummary",
                        "Does Not Exist",
                        ""});
#line 90
 testRunner.Then("I see", ((string)(null)), table10, "Then ");
#line 95
 testRunner.When("I choose WorkExperienceYes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 96
 testRunner.And("I choose SaveWorkExperience", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Rule",
                        "Value"});
            table11.AddRow(new string[] {
                        "WorkExperienceValidationErrorsCount",
                        "Equals",
                        "5"});
#line 97
 testRunner.Then("I see", ((string)(null)), table11, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table12.AddRow(new string[] {
                        "WorkEmployer",
                        "WorkEmployer"});
            table12.AddRow(new string[] {
                        "WorkTitle",
                        "WorkTitle"});
            table12.AddRow(new string[] {
                        "WorkRole",
                        "WorkRole"});
            table12.AddRow(new string[] {
                        "WorkFromYear",
                        "2011"});
            table12.AddRow(new string[] {
                        "WorkToYear",
                        "2012"});
#line 100
 testRunner.When("I enter data", ((string)(null)), table12, "When ");
#line 107
 testRunner.And("I choose SaveWorkExperience", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 109
 testRunner.And("I choose SaveWorkExperience", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 110
 testRunner.Then("I wait for 30 seconds to see WorkExperienceSummary", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Rule",
                        "Value"});
            table13.AddRow(new string[] {
                        "WorkExperiencesCount",
                        "Equals",
                        "1"});
#line 111
 testRunner.Then("I see", ((string)(null)), table13, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Rule",
                        "Value"});
            table14.AddRow(new string[] {
                        "Employer",
                        "Equals",
                        "WorkEmployer"});
            table14.AddRow(new string[] {
                        "JobTitle",
                        "Equals",
                        "WorkTitle"});
            table14.AddRow(new string[] {
                        "MainDuties",
                        "Equals",
                        "WorkRole"});
#line 114
 testRunner.And("I am on WorkExperienceSummaryItems list item matching criteria", ((string)(null)), table14, "And ");
#line 119
 testRunner.When("I choose RemoveWorkExperienceLink", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 120
 testRunner.And("I am on the ApprenticeshipApplicationPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Rule",
                        "Value"});
            table15.AddRow(new string[] {
                        "WorkExperienceSummary",
                        "Does Not Exist",
                        ""});
#line 121
 testRunner.Then("I see", ((string)(null)), table15, "Then ");
#line 126
 testRunner.When("I choose TrainingCoursesYes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 127
 testRunner.And("I choose SaveTrainingCourseButton", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Rule",
                        "Value"});
            table16.AddRow(new string[] {
                        "TrainingCourseValidationErrorsCount",
                        "Equals",
                        "4"});
#line 128
 testRunner.Then("I see", ((string)(null)), table16, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table17.AddRow(new string[] {
                        "TrainingCourseProvider",
                        "TrainingCourseProvider"});
            table17.AddRow(new string[] {
                        "TrainingCourseTitle",
                        "TrainingCourseTitle"});
            table17.AddRow(new string[] {
                        "TrainingCourseFromYear",
                        "2011"});
            table17.AddRow(new string[] {
                        "TrainingCourseToYear",
                        "2012"});
#line 131
 testRunner.When("I enter data", ((string)(null)), table17, "When ");
#line 137
 testRunner.And("I choose SaveTrainingCourseButton", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 139
 testRunner.And("I choose SaveTrainingCourseButton", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 140
 testRunner.Then("I wait for 30 seconds to see TrainingCourseSummary", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Rule",
                        "Value"});
            table18.AddRow(new string[] {
                        "TrainingCourseCount",
                        "Equals",
                        "1"});
#line 141
 testRunner.Then("I see", ((string)(null)), table18, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Rule",
                        "Value"});
            table19.AddRow(new string[] {
                        "Provider",
                        "Equals",
                        "TrainingCourseProvider"});
            table19.AddRow(new string[] {
                        "CourseTitle",
                        "Equals",
                        "TrainingCourseTitle"});
#line 144
 testRunner.And("I am on TrainingCourseSummaryItems list item matching criteria", ((string)(null)), table19, "And ");
#line 148
 testRunner.When("I choose RemoveTrainingCourseLink", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 149
 testRunner.And("I am on the ApprenticeshipApplicationPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Rule",
                        "Value"});
            table20.AddRow(new string[] {
                        "TrainingCourseSummary",
                        "Does Not Exist",
                        ""});
#line 150
 testRunner.Then("I see", ((string)(null)), table20, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table21.AddRow(new string[] {
                        "EducationNameOfSchool",
                        "SchoolName"});
            table21.AddRow(new string[] {
                        "EducationFromYear",
                        "2010"});
            table21.AddRow(new string[] {
                        "EducationToYear",
                        "2012"});
            table21.AddRow(new string[] {
                        "WhatAreYourStrengths",
                        "My strengths"});
            table21.AddRow(new string[] {
                        "WhatCanYouImprove",
                        "What can I improve"});
            table21.AddRow(new string[] {
                        "HobbiesAndInterests",
                        "Hobbies and interests"});
#line 155
 testRunner.When("I enter data", ((string)(null)), table21, "When ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table22.AddRow(new string[] {
                        "Candidate_EmployerQuestionAnswers_CandidateAnswer1",
                        "Emp 1"});
            table22.AddRow(new string[] {
                        "Candidate_EmployerQuestionAnswers_CandidateAnswer2",
                        "Emp 2"});
#line 163
 testRunner.And("I enter employer question data if present", ((string)(null)), table22, "And ");
#line 167
 testRunner.And("I choose QualificationsYes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Rule",
                        "Value"});
            table23.AddRow(new string[] {
                        "Text",
                        "Equals",
                        "GCSE"});
#line 168
 testRunner.And("I am on QualificationTypeDropdown list item matching criteria", ((string)(null)), table23, "And ");
#line 171
 testRunner.And("I choose WrappedElement", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 172
 testRunner.And("I am on the ApprenticeshipApplicationPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table24.AddRow(new string[] {
                        "SubjectYear",
                        "2012"});
            table24.AddRow(new string[] {
                        "SubjectName",
                        "SubjectName"});
            table24.AddRow(new string[] {
                        "SubjectGrade",
                        "SubjectGrade"});
#line 173
 testRunner.And("I enter data", ((string)(null)), table24, "And ");
#line 178
 testRunner.And("I choose SaveQualification", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 179
 testRunner.When("I choose WorkExperienceYes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table25.AddRow(new string[] {
                        "WorkEmployer",
                        "WorkEmployer"});
            table25.AddRow(new string[] {
                        "WorkTitle",
                        "WorkTitle"});
            table25.AddRow(new string[] {
                        "WorkRole",
                        "WorkRole"});
            table25.AddRow(new string[] {
                        "WorkFromYear",
                        "2011"});
            table25.AddRow(new string[] {
                        "WorkToYear",
                        "2012"});
#line 180
 testRunner.And("I enter data", ((string)(null)), table25, "And ");
#line 187
 testRunner.And("I choose SaveWorkExperience", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 189
 testRunner.When("I choose TrainingCoursesYes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table26.AddRow(new string[] {
                        "TrainingCourseProvider",
                        "TrainingProvider"});
            table26.AddRow(new string[] {
                        "TrainingCourseTitle",
                        "TrainingCourseTitle"});
            table26.AddRow(new string[] {
                        "TrainingCourseFromYear",
                        "2011"});
            table26.AddRow(new string[] {
                        "TrainingCourseToYear",
                        "2012"});
#line 190
 testRunner.And("I enter data", ((string)(null)), table26, "And ");
#line 196
 testRunner.And("I choose SaveTrainingCourseButton", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 198
 testRunner.And("I choose SaveButton", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 199
 testRunner.Then("I wait to see ApplicationSavedMessage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Rule",
                        "Value"});
            table27.AddRow(new string[] {
                        "ApplicationSavedMessage",
                        "Ends With",
                        "my applications"});
#line 200
 testRunner.And("I see", ((string)(null)), table27, "And ");
#line 203
 testRunner.When("I choose MyApplicationsLink", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 204
 testRunner.Then("I am on the MyApplicationsPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Rule",
                        "Value"});
            table28.AddRow(new string[] {
                        "DraftApplicationsCount",
                        "Equals",
                        "1"});
#line 205
 testRunner.And("I see", ((string)(null)), table28, "And ");
#line 208
 testRunner.When("I choose ResumeLink", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 209
 testRunner.Then("I wait 120 second for the ApprenticeshipApplicationPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 210
 testRunner.When("I am on the ApprenticeshipApplicationPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Rule",
                        "Value"});
            table29.AddRow(new string[] {
                        "QualificationsSummaryCount",
                        "Equals",
                        "1"});
#line 211
 testRunner.Then("I see", ((string)(null)), table29, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Rule",
                        "Value"});
            table30.AddRow(new string[] {
                        "Subject",
                        "Equals",
                        "SubjectName"});
            table30.AddRow(new string[] {
                        "Year",
                        "Equals",
                        "2012"});
            table30.AddRow(new string[] {
                        "Grade",
                        "Equals",
                        "SubjectGrade"});
#line 214
 testRunner.And("I am on QualificationsSummaryItems list item matching criteria", ((string)(null)), table30, "And ");
#line 219
 testRunner.And("I am on the ApprenticeshipApplicationPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Rule",
                        "Value"});
            table31.AddRow(new string[] {
                        "WorkExperiencesCount",
                        "Equals",
                        "1"});
#line 220
 testRunner.And("I see", ((string)(null)), table31, "And ");
#line hidden
            TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Rule",
                        "Value"});
            table32.AddRow(new string[] {
                        "Employer",
                        "Equals",
                        "WorkEmployer"});
            table32.AddRow(new string[] {
                        "JobTitle",
                        "Equals",
                        "WorkTitle"});
            table32.AddRow(new string[] {
                        "MainDuties",
                        "Equals",
                        "WorkRole"});
#line 223
 testRunner.And("I am on WorkExperienceSummaryItems list item matching criteria", ((string)(null)), table32, "And ");
#line 228
 testRunner.When("I am on the ApprenticeshipApplicationPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 229
 testRunner.And("I choose ApplyButton", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 230
 testRunner.Then("I am on the ApprenticeshipApplicationPreviewPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Rule",
                        "Value"});
            table33.AddRow(new string[] {
                        "ApplicationSavedTopMessage",
                        "Ends With",
                        "my applications"});
            table33.AddRow(new string[] {
                        "ApplicationSavedBottomMessage",
                        "Ends With",
                        "my applications"});
            table33.AddRow(new string[] {
                        "EducationNameOfSchool",
                        "Equals",
                        "SchoolName"});
            table33.AddRow(new string[] {
                        "EducationFromYear",
                        "Equals",
                        "2010"});
            table33.AddRow(new string[] {
                        "EducationToYear",
                        "Equals",
                        "2012"});
            table33.AddRow(new string[] {
                        "NoQualificationsMessage",
                        "Does Not Exist",
                        ""});
            table33.AddRow(new string[] {
                        "NoWorkExperienceMessage",
                        "Does Not Exist",
                        ""});
            table33.AddRow(new string[] {
                        "NoTrainingCoursesMessage",
                        "Does Not Exist",
                        ""});
            table33.AddRow(new string[] {
                        "WhatAreYourStrengths",
                        "Equals",
                        "My strengths"});
            table33.AddRow(new string[] {
                        "WhatCanYouImprove",
                        "Equals",
                        "What can I improve"});
            table33.AddRow(new string[] {
                        "HobbiesAndInterests",
                        "Equals",
                        "Hobbies and interests"});
#line 231
 testRunner.And("I see", ((string)(null)), table33, "And ");
#line 244
 testRunner.When("I choose AcceptSubmit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 245
 testRunner.Then("I am on the ApprenticeshipApplicationPreviewPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 246
 testRunner.When("I choose SubmitApplication", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 247
 testRunner.Then("I am on the ApprenticeshipApplicationCompletePage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 248
 testRunner.When("I choose MyApplicationsLink", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 249
 testRunner.Then("I am on the MyApplicationsPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Rule",
                        "Value"});
            table34.AddRow(new string[] {
                        "SubmittedApplicationsCount",
                        "Equals",
                        "1"});
#line 250
 testRunner.And("I see", ((string)(null)), table34, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("As a candidate I would like to see my apprenticeship application as submitted")]
        [NUnit.Framework.CategoryAttribute("US154")]
        public virtual void AsACandidateIWouldLikeToSeeMyApprenticeshipApplicationAsSubmitted()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("As a candidate I would like to see my apprenticeship application as submitted", new string[] {
                        "US154"});
#line 255
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 256
 testRunner.Given("I have registered a new candidate", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 257
 testRunner.When("I select the \"first\" apprenticeship vacancy in location \"N7 8LS\" that can apply b" +
                    "y this website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 258
 testRunner.Then("I am on the ApprenticeshipDetailsPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 259
 testRunner.When("I choose ApplyButton", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 260
 testRunner.Then("I am on the ApprenticeshipApplicationPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 261
 testRunner.When("I choose SupportMeYes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table35.AddRow(new string[] {
                        "EducationNameOfSchool",
                        "InProgress"});
            table35.AddRow(new string[] {
                        "EducationFromYear",
                        "2010"});
            table35.AddRow(new string[] {
                        "EducationToYear",
                        "2012"});
            table35.AddRow(new string[] {
                        "WhatAreYourStrengths",
                        "My strengths"});
            table35.AddRow(new string[] {
                        "WhatCanYouImprove",
                        "What can I improve"});
            table35.AddRow(new string[] {
                        "HobbiesAndInterests",
                        "Hobbies and interests"});
            table35.AddRow(new string[] {
                        "WhatCanWeDoToSupportYou",
                        "What can we do to support you"});
#line 262
 testRunner.And("I enter data", ((string)(null)), table35, "And ");
#line hidden
            TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table36.AddRow(new string[] {
                        "Candidate_EmployerQuestionAnswers_CandidateAnswer1",
                        "Emp 1"});
            table36.AddRow(new string[] {
                        "Candidate_EmployerQuestionAnswers_CandidateAnswer2",
                        "Emp 2"});
#line 271
 testRunner.And("I enter employer question data if present", ((string)(null)), table36, "And ");
#line 275
 testRunner.And("I choose ApplyButton", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 276
 testRunner.Then("I am on the ApprenticeshipApplicationPreviewPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 277
 testRunner.When("I choose AcceptSubmit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 278
 testRunner.Then("I am on the ApprenticeshipApplicationPreviewPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 279
 testRunner.When("I choose SubmitApplication", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 280
 testRunner.Then("I am on the ApprenticeshipApplicationCompletePage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 281
 testRunner.When("I wait 5 seconds", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 282
 testRunner.When("I choose MyApplicationsLink", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 283
 testRunner.Then("I am on the MyApplicationsPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Rule",
                        "Value"});
            table37.AddRow(new string[] {
                        "SubmittedApplicationsCount",
                        "Equals",
                        "1"});
#line 284
 testRunner.And("I see", ((string)(null)), table37, "And ");
#line hidden
            TechTalk.SpecFlow.Table table38 = new TechTalk.SpecFlow.Table(new string[] {
                        "VacancyId"});
            table38.AddRow(new string[] {
                        "{VacancyId}"});
#line 287
 testRunner.And("I navigate to the ApprenticeshipDetailsPage page with parameters", ((string)(null)), table38, "And ");
#line hidden
            TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Rule",
                        "Value"});
            table39.AddRow(new string[] {
                        "TrackApplicationStatusLink",
                        "Exists",
                        ""});
#line 290
 testRunner.Then("I see", ((string)(null)), table39, "Then ");
#line 293
 testRunner.When("I choose TrackApplicationStatusLink", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 294
 testRunner.Then("I am on the MyApplicationsPage page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
