INSERT INTO [Vacancy].[Vacancy]
    ([VacancyReferenceNumber]
    ,[VacancyTypeCode]
    ,[VacancyStatusCode]
    ,[VacancyLocationTypeCode]
    ,[ParentVacancyId]
    ,[EmployerVacancyPartyId]
    ,[OwnerVacancyPartyId]
    ,[ManagerVacancyPartyId]
    ,[DeliveryProviderVacancyPartyId]
    ,[ContractOwnerVacancyPartyId]
    ,[OriginalContractOwnerVacancyPartyId]
    ,[Title]
    ,[TitleComment]
    ,[ShortDescription]
    ,[ShortDescriptionComment]
    ,[LongDescription]
    ,[LongDescriptionComment]
    ,[TrainingTypeCode]
    ,[FrameworkId]
    ,[FrameworkIdComment]
    ,[StandardId]
    ,[StandardIdComment]
    ,[LevelCode]
    ,[LevelCodeComment]
    ,[WageValue]
    ,[WageTypeCode]
    ,[AV_WageText]
    ,[WageComment]
    ,[PossibleStartDateDate]
    ,[PossibleStartDateComment]
    ,[ClosingDate]
    ,[ClosingDateComment]
    ,[StartDate]
    ,[AV_InterviewStartDate]
    ,[DurationValue]
    ,[DurationTypeCode]
    ,[DurationComment]
    ,[WorkingWeekText]
    ,[HoursPerWeek]
    ,[AV_ContactName]
    ,[EmployerDescription]
    ,[IsDirectApplication]
    ,[DirectApplicationUrl]
    ,[DirectApplicationUrlComment]
    ,[DirectApplicationInstructions]
    ,[DirectApplicationInstructionsComment]
    ,[DesiredSkills]
    ,[DesiredSkillsComment]
    ,[FutureProspects]
    ,[FutureProspectsComment]
    ,[PersonalQualities]
    ,[PersonalQualitiesComment]
    ,[ThingsToConsider]
    ,[ThingsToConsiderComment]
    ,[DesiredQualifications]
    ,[DesiredQualificationsComment]
    ,[FirstQuestion]
    ,[FirstQuestionComment]
    ,[SecondQuestion]
    ,[SecondQuestionComment]
    ,[QAUserName]
    ,[DateQAApproved])
     VALUES
    (1
    ,'A'
    ,'DRA'
    ,'S'
    ,NULL
    ,1
    ,2
    ,2
    ,2
    ,2
    ,NULL
    ,'Test vacancy'
    ,NULL
    ,'Short description for the test vacancy'
    ,NULL
    ,'Long description for the test vacancy'
    ,NULL
    ,'F'
    ,1
    ,NULL
    ,NULL 
    ,NULL
    ,2
    ,NULL
    ,NULL
    ,NULL /* WAGE TYPE CODE */
    ,'AV_WageText'
    ,NULL
    ,'2017-02-15'
    ,NULL
    ,'2017-03-15'
    ,NULL
    ,'2017-03-15'
    ,'2017-03-01'
    ,2
    ,'Y'
    ,NULL
    ,'9:00-17:00'
    ,40
    ,'AV_ContactName'
    ,'EmployerDescription'
    ,0
    ,NULL
    ,NULL
    ,NULL
    ,NULL
    ,'DesiredSkills'
    ,NULL
    ,'FutureProspects'
    ,NULL
    ,'PersonalQualities'
    ,NULL
    ,'ThingsToConsider'
    ,NULL
    ,'DesiredQualifications'
    ,NULL
    ,'FirstQuestion'
    ,NULL
    ,'SecondQuestion'
    ,NULL
    ,NULL
    ,NULL
)