create procedure [sp_MSins_dboVacancyLocation]
    @c1 int,
    @c2 int,
    @c3 smallint,
    @c4 nvarchar(50),
    @c5 nvarchar(50),
    @c6 nvarchar(50),
    @c7 nvarchar(50),
    @c8 nvarchar(50),
    @c9 nvarchar(40),
    @c10 int,
    @c11 nvarchar(8),
    @c12 int,
    @c13 int,
    @c14 int,
    @c15 decimal(13,10),
    @c16 decimal(13,10),
    @c17 nvarchar(256)
as
begin  
	insert into [dbo].[VacancyLocation](
		[VacancyLocationId],
		[VacancyId],
		[NumberofPositions],
		[AddressLine1],
		[AddressLine2],
		[AddressLine3],
		[AddressLine4],
		[AddressLine5],
		[Town],
		[CountyId],
		[PostCode],
		[LocalAuthorityId],
		[GeocodeEasting],
		[GeocodeNorthing],
		[Longitude],
		[Latitude],
		[EmployersWebsite]
	) values (
    @c1,
    @c2,
    @c3,
    @c4,
    @c5,
    @c6,
    @c7,
    @c8,
    @c9,
    @c10,
    @c11,
    @c12,
    @c13,
    @c14,
    @c15,
    @c16,
    @c17	) 
end