create procedure [sp_MSins_dboEmployerContact]
    @c1 int,
    @c2 int,
    @c3 nvarchar(50),
    @c4 nvarchar(50),
    @c5 nvarchar(50),
    @c6 nvarchar(50),
    @c7 nvarchar(50),
    @c8 nvarchar(50),
    @c9 int,
    @c10 nvarchar(8),
    @c11 int,
    @c12 nvarchar(50),
    @c13 nvarchar(50),
    @c14 nvarchar(16),
    @c15 nvarchar(16),
    @c16 int,
    @c17 nvarchar(50)
as
begin  
	insert into [dbo].[EmployerContact](
		[EmployerContactId],
		[PersonId],
		[AddressLine1],
		[AddressLine2],
		[AddressLine3],
		[AddressLine4],
		[AddressLine5],
		[Town],
		[CountyId],
		[PostCode],
		[LocalAuthorityId],
		[JobTitle],
		[Department],
		[FaxNumber],
		[AlternatePhoneNumber],
		[ContactPreferenceTypeId],
		[Availability]
	) values (
    @c1,
    @c2,
    @c3,
    @c4,
    @c5,
    @c6,
    @c7,
    @c8,
    @c9,
    @c10,
    @c11,
    @c12,
    @c13,
    @c14,
    @c15,
    @c16,
    @c17	) 
end