create procedure [sp_MSupd_dboProviderSite]
		@c1 int = NULL,
		@c2 nvarchar(255) = NULL,
		@c3 nvarchar(255) = NULL,
		@c4 int = NULL,
		@c5 nvarchar(50) = NULL,
		@c6 nvarchar(50) = NULL,
		@c7 nvarchar(50) = NULL,
		@c8 nvarchar(50) = NULL,
		@c9 nvarchar(50) = NULL,
		@c10 nvarchar(50) = NULL,
		@c11 int = NULL,
		@c12 nvarchar(8) = NULL,
		@c13 int = NULL,
		@c14 int = NULL,
		@c15 decimal(13,10) = NULL,
		@c16 decimal(13,10) = NULL,
		@c17 int = NULL,
		@c18 int = NULL,
		@c19 nvarchar(255) = NULL,
		@c20 nvarchar(max) = NULL,
		@c21 nvarchar(max) = NULL,
		@c22 nvarchar(100) = NULL,
		@c23 bit = NULL,
		@c24 nvarchar(256) = NULL,
		@c25 nvarchar(256) = NULL,
		@c26 bit = NULL,
		@c27 int = NULL,
		@c28 bit = NULL,
		@c29 nvarchar(1000) = NULL,
		@pkc1 int = NULL,
		@bitmap binary(4)
as
begin  
update [dbo].[ProviderSite] set
		[FullName] = case substring(@bitmap,1,1) & 2 when 2 then @c2 else [FullName] end,
		[TradingName] = case substring(@bitmap,1,1) & 4 when 4 then @c3 else [TradingName] end,
		[EDSURN] = case substring(@bitmap,1,1) & 8 when 8 then @c4 else [EDSURN] end,
		[AddressLine1] = case substring(@bitmap,1,1) & 16 when 16 then @c5 else [AddressLine1] end,
		[AddressLine2] = case substring(@bitmap,1,1) & 32 when 32 then @c6 else [AddressLine2] end,
		[AddressLine3] = case substring(@bitmap,1,1) & 64 when 64 then @c7 else [AddressLine3] end,
		[AddressLine4] = case substring(@bitmap,1,1) & 128 when 128 then @c8 else [AddressLine4] end,
		[AddressLine5] = case substring(@bitmap,2,1) & 1 when 1 then @c9 else [AddressLine5] end,
		[Town] = case substring(@bitmap,2,1) & 2 when 2 then @c10 else [Town] end,
		[CountyId] = case substring(@bitmap,2,1) & 4 when 4 then @c11 else [CountyId] end,
		[PostCode] = case substring(@bitmap,2,1) & 8 when 8 then @c12 else [PostCode] end,
		[LocalAuthorityId] = case substring(@bitmap,2,1) & 16 when 16 then @c13 else [LocalAuthorityId] end,
		[ManagingAreaID] = case substring(@bitmap,2,1) & 32 when 32 then @c14 else [ManagingAreaID] end,
		[Longitude] = case substring(@bitmap,2,1) & 64 when 64 then @c15 else [Longitude] end,
		[Latitude] = case substring(@bitmap,2,1) & 128 when 128 then @c16 else [Latitude] end,
		[GeocodeEasting] = case substring(@bitmap,3,1) & 1 when 1 then @c17 else [GeocodeEasting] end,
		[GeocodeNorthing] = case substring(@bitmap,3,1) & 2 when 2 then @c18 else [GeocodeNorthing] end,
		[OwnerOrganisation] = case substring(@bitmap,3,1) & 4 when 4 then @c19 else [OwnerOrganisation] end,
		[EmployerDescription] = case substring(@bitmap,3,1) & 8 when 8 then @c20 else [EmployerDescription] end,
		[CandidateDescription] = case substring(@bitmap,3,1) & 16 when 16 then @c21 else [CandidateDescription] end,
		[WebPage] = case substring(@bitmap,3,1) & 32 when 32 then @c22 else [WebPage] end,
		[OutofDate] = case substring(@bitmap,3,1) & 64 when 64 then @c23 else [OutofDate] end,
		[ContactDetailsForEmployer] = case substring(@bitmap,3,1) & 128 when 128 then @c24 else [ContactDetailsForEmployer] end,
		[ContactDetailsForCandidate] = case substring(@bitmap,4,1) & 1 when 1 then @c25 else [ContactDetailsForCandidate] end,
		[HideFromSearch] = case substring(@bitmap,4,1) & 2 when 2 then @c26 else [HideFromSearch] end,
		[TrainingProviderStatusTypeId] = case substring(@bitmap,4,1) & 4 when 4 then @c27 else [TrainingProviderStatusTypeId] end,
		[IsRecruitmentAgency] = case substring(@bitmap,4,1) & 8 when 8 then @c28 else [IsRecruitmentAgency] end,
		[ContactDetailsAsARecruitmentAgency] = case substring(@bitmap,4,1) & 16 when 16 then @c29 else [ContactDetailsAsARecruitmentAgency] end
where [ProviderSiteID] = @pkc1
if @@rowcount = 0
    if @@microsoftversion>0x07320000
        exec sp_MSreplraiserror 20598
end