create procedure [sp_MSins_dboProviderSite]
    @c1 int,
    @c2 nvarchar(255),
    @c3 nvarchar(255),
    @c4 int,
    @c5 nvarchar(50),
    @c6 nvarchar(50),
    @c7 nvarchar(50),
    @c8 nvarchar(50),
    @c9 nvarchar(50),
    @c10 nvarchar(50),
    @c11 int,
    @c12 nvarchar(8),
    @c13 int,
    @c14 int,
    @c15 decimal(13,10),
    @c16 decimal(13,10),
    @c17 int,
    @c18 int,
    @c19 nvarchar(255),
    @c20 nvarchar(max),
    @c21 nvarchar(max),
    @c22 nvarchar(100),
    @c23 bit,
    @c24 nvarchar(256),
    @c25 nvarchar(256),
    @c26 bit,
    @c27 int,
    @c28 bit,
    @c29 nvarchar(1000)
as
begin  
	insert into [dbo].[ProviderSite](
		[ProviderSiteID],
		[FullName],
		[TradingName],
		[EDSURN],
		[AddressLine1],
		[AddressLine2],
		[AddressLine3],
		[AddressLine4],
		[AddressLine5],
		[Town],
		[CountyId],
		[PostCode],
		[LocalAuthorityId],
		[ManagingAreaID],
		[Longitude],
		[Latitude],
		[GeocodeEasting],
		[GeocodeNorthing],
		[OwnerOrganisation],
		[EmployerDescription],
		[CandidateDescription],
		[WebPage],
		[OutofDate],
		[ContactDetailsForEmployer],
		[ContactDetailsForCandidate],
		[HideFromSearch],
		[TrainingProviderStatusTypeId],
		[IsRecruitmentAgency],
		[ContactDetailsAsARecruitmentAgency]
	) values (
    @c1,
    @c2,
    @c3,
    @c4,
    @c5,
    @c6,
    @c7,
    @c8,
    @c9,
    @c10,
    @c11,
    @c12,
    @c13,
    @c14,
    @c15,
    @c16,
    @c17,
    @c18,
    @c19,
    @c20,
    @c21,
    @c22,
    @c23,
    @c24,
    @c25,
    @c26,
    @c27,
    @c28,
    @c29	) 
end