create procedure [sp_MSupd_dboEmployer]
		@c1 int = NULL,
		@c2 int = NULL,
		@c3 nvarchar(255) = NULL,
		@c4 nvarchar(255) = NULL,
		@c5 nvarchar(50) = NULL,
		@c6 nvarchar(50) = NULL,
		@c7 nvarchar(50) = NULL,
		@c8 nvarchar(50) = NULL,
		@c9 nvarchar(50) = NULL,
		@c10 nvarchar(50) = NULL,
		@c11 int = NULL,
		@c12 nvarchar(8) = NULL,
		@c13 int = NULL,
		@c14 decimal(13,10) = NULL,
		@c15 decimal(13,10) = NULL,
		@c16 int = NULL,
		@c17 int = NULL,
		@c18 int = NULL,
		@c19 int = NULL,
		@c20 int = NULL,
		@c21 varchar(255) = NULL,
		@c22 varchar(8) = NULL,
		@c23 int = NULL,
		@c24 nvarchar(50) = NULL,
		@c25 datetime = NULL,
		@c26 int = NULL,
		@c27 bit = NULL,
		@c28 bit = NULL,
		@pkc1 int = NULL,
		@bitmap binary(4)
as
begin  
update [dbo].[Employer] set
		[EdsUrn] = case substring(@bitmap,1,1) & 2 when 2 then @c2 else [EdsUrn] end,
		[FullName] = case substring(@bitmap,1,1) & 4 when 4 then @c3 else [FullName] end,
		[TradingName] = case substring(@bitmap,1,1) & 8 when 8 then @c4 else [TradingName] end,
		[AddressLine1] = case substring(@bitmap,1,1) & 16 when 16 then @c5 else [AddressLine1] end,
		[AddressLine2] = case substring(@bitmap,1,1) & 32 when 32 then @c6 else [AddressLine2] end,
		[AddressLine3] = case substring(@bitmap,1,1) & 64 when 64 then @c7 else [AddressLine3] end,
		[AddressLine4] = case substring(@bitmap,1,1) & 128 when 128 then @c8 else [AddressLine4] end,
		[AddressLine5] = case substring(@bitmap,2,1) & 1 when 1 then @c9 else [AddressLine5] end,
		[Town] = case substring(@bitmap,2,1) & 2 when 2 then @c10 else [Town] end,
		[CountyId] = case substring(@bitmap,2,1) & 4 when 4 then @c11 else [CountyId] end,
		[PostCode] = case substring(@bitmap,2,1) & 8 when 8 then @c12 else [PostCode] end,
		[LocalAuthorityId] = case substring(@bitmap,2,1) & 16 when 16 then @c13 else [LocalAuthorityId] end,
		[Longitude] = case substring(@bitmap,2,1) & 32 when 32 then @c14 else [Longitude] end,
		[Latitude] = case substring(@bitmap,2,1) & 64 when 64 then @c15 else [Latitude] end,
		[GeocodeEasting] = case substring(@bitmap,2,1) & 128 when 128 then @c16 else [GeocodeEasting] end,
		[GeocodeNorthing] = case substring(@bitmap,3,1) & 1 when 1 then @c17 else [GeocodeNorthing] end,
		[PrimaryContact] = case substring(@bitmap,3,1) & 2 when 2 then @c18 else [PrimaryContact] end,
		[NumberofEmployeesAtSite] = case substring(@bitmap,3,1) & 4 when 4 then @c19 else [NumberofEmployeesAtSite] end,
		[NumberOfEmployeesInGroup] = case substring(@bitmap,3,1) & 8 when 8 then @c20 else [NumberOfEmployeesInGroup] end,
		[OwnerOrgnistaion] = case substring(@bitmap,3,1) & 16 when 16 then @c21 else [OwnerOrgnistaion] end,
		[CompanyRegistrationNumber] = case substring(@bitmap,3,1) & 32 when 32 then @c22 else [CompanyRegistrationNumber] end,
		[TotalVacanciesPosted] = case substring(@bitmap,3,1) & 64 when 64 then @c23 else [TotalVacanciesPosted] end,
		[BeingSupportedBy] = case substring(@bitmap,3,1) & 128 when 128 then @c24 else [BeingSupportedBy] end,
		[LockedForSupportUntil] = case substring(@bitmap,4,1) & 1 when 1 then @c25 else [LockedForSupportUntil] end,
		[EmployerStatusTypeId] = case substring(@bitmap,4,1) & 2 when 2 then @c26 else [EmployerStatusTypeId] end,
		[DisableAllowed] = case substring(@bitmap,4,1) & 4 when 4 then @c27 else [DisableAllowed] end,
		[TrackingAllowed] = case substring(@bitmap,4,1) & 8 when 8 then @c28 else [TrackingAllowed] end
where [EmployerId] = @pkc1
if @@rowcount = 0
    if @@microsoftversion>0x07320000
        exec sp_MSreplraiserror 20598
end