create procedure [sp_MSins_dboMessage]
    @c1 int,
    @c2 int,
    @c3 int,
    @c4 int,
    @c5 int,
    @c6 datetime,
    @c7 int,
    @c8 nvarchar(max),
    @c9 nvarchar(1000),
    @c10 bit,
    @c11 bit,
    @c12 int,
    @c13 datetime,
    @c14 nvarchar(250),
    @c15 nvarchar(250),
    @c16 datetime
as
begin  
	insert into [dbo].[Message](
		[MessageId],
		[Sender],
		[SenderType],
		[Recipient],
		[RecipientType],
		[MessageDate],
		[MessageEventId],
		[Text],
		[Title],
		[IsRead],
		[IsDeleted],
		[MessageCategoryID],
		[ReadDate],
		[DeletedBy],
		[ReadByFirst],
		[DeletedDate]
	) values (
    @c1,
    @c2,
    @c3,
    @c4,
    @c5,
    @c6,
    @c7,
    @c8,
    @c9,
    @c10,
    @c11,
    @c12,
    @c13,
    @c14,
    @c15,
    @c16	) 
end