create procedure [sp_MSins_dboSavedSearchCriteria]
    @c1 int,
    @c2 int,
    @c3 nvarchar(50),
    @c4 int,
    @c5 int,
    @c6 nvarchar(8),
    @c7 decimal(13,10),
    @c8 decimal(13,10),
    @c9 int,
    @c10 int,
    @c11 smallint,
    @c12 smallint,
    @c13 smallint,
    @c14 int,
    @c15 nvarchar(255),
    @c16 nvarchar(255),
    @c17 nvarchar(100),
    @c18 datetime,
    @c19 bit,
    @c20 bit,
    @c21 int,
    @c22 int,
    @c23 int
as
begin  
	insert into [dbo].[SavedSearchCriteria](
		[SavedSearchCriteriaId],
		[CandidateId],
		[Name],
		[SearchType],
		[CountyId],
		[Postcode],
		[Longitude],
		[Latitude],
		[GeocodeEasting],
		[GeocodeNorthing],
		[DistanceFromPostcode],
		[MinWages],
		[MaxWages],
		[VacancyReferenceNumber],
		[Employer],
		[TrainingProvider],
		[Keywords],
		[DateSearched],
		[BackgroundSearch],
		[AlertSent],
		[CountBackgroundMatches],
		[VacancyPostedSince],
		[ApprenticeshipTypeId]
	) values (
    @c1,
    @c2,
    @c3,
    @c4,
    @c5,
    @c6,
    @c7,
    @c8,
    @c9,
    @c10,
    @c11,
    @c12,
    @c13,
    @c14,
    @c15,
    @c16,
    @c17,
    @c18,
    @c19,
    @c20,
    @c21,
    @c22,
    @c23	) 
end