create procedure [sp_MSins_dboVacancy]
    @c1 int,
    @c2 int,
    @c3 int,
    @c4 nvarchar(100),
    @c5 int,
    @c6 nvarchar(50),
    @c7 nvarchar(50),
    @c8 nvarchar(50),
    @c9 nvarchar(50),
    @c10 nvarchar(50),
    @c11 nvarchar(40),
    @c12 int,
    @c13 nvarchar(8),
    @c14 int,
    @c15 int,
    @c16 int,
    @c17 decimal(13,10),
    @c18 decimal(13,10),
    @c19 int,
    @c20 nvarchar(100),
    @c21 int,
    @c22 nvarchar(256),
    @c23 nvarchar(max),
    @c24 money,
    @c25 int,
    @c26 nvarchar(50),
    @c27 smallint,
    @c28 datetime,
    @c29 datetime,
    @c30 datetime,
    @c31 nvarchar(50),
    @c32 nvarchar(50),
    @c33 int,
    @c34 nvarchar(255),
    @c35 nvarchar(max),
    @c36 nvarchar(256),
    @c37 int,
    @c38 bit,
    @c39 nvarchar(max),
    @c40 nvarchar(256),
    @c41 nvarchar(50),
    @c42 datetime,
    @c43 int,
    @c44 int,
    @c45 int,
    @c46 int,
    @c47 int,
    @c48 int,
    @c49 int,
    @c50 bit,
    @c51 int,
    @c52 bit
as
begin  
	insert into [dbo].[Vacancy](
		[VacancyId],
		[VacancyOwnerRelationshipId],
		[VacancyReferenceNumber],
		[ContactName],
		[VacancyStatusId],
		[AddressLine1],
		[AddressLine2],
		[AddressLine3],
		[AddressLine4],
		[AddressLine5],
		[Town],
		[CountyId],
		[PostCode],
		[LocalAuthorityId],
		[GeocodeEasting],
		[GeocodeNorthing],
		[Longitude],
		[Latitude],
		[ApprenticeshipFrameworkId],
		[Title],
		[ApprenticeshipType],
		[ShortDescription],
		[Description],
		[WeeklyWage],
		[WageType],
		[WageText],
		[NumberofPositions],
		[ApplicationClosingDate],
		[InterviewsFromDate],
		[ExpectedStartDate],
		[ExpectedDuration],
		[WorkingWeek],
		[NumberOfViews],
		[EmployerAnonymousName],
		[EmployerDescription],
		[EmployersWebsite],
		[MaxNumberofApplications],
		[ApplyOutsideNAVMS],
		[EmployersApplicationInstructions],
		[EmployersRecruitmentWebsite],
		[BeingSupportedBy],
		[LockedForSupportUntil],
		[NoOfOfflineApplicants],
		[MasterVacancyId],
		[VacancyLocationTypeId],
		[NoOfOfflineSystemApplicants],
		[VacancyManagerID],
		[DeliveryOrganisationID],
		[ContractOwnerID],
		[SmallEmployerWageIncentive],
		[OriginalContractOwnerId],
		[VacancyManagerAnonymous]
	) values (
    @c1,
    @c2,
    @c3,
    @c4,
    @c5,
    @c6,
    @c7,
    @c8,
    @c9,
    @c10,
    @c11,
    @c12,
    @c13,
    @c14,
    @c15,
    @c16,
    @c17,
    @c18,
    @c19,
    @c20,
    @c21,
    @c22,
    @c23,
    @c24,
    @c25,
    @c26,
    @c27,
    @c28,
    @c29,
    @c30,
    @c31,
    @c32,
    @c33,
    @c34,
    @c35,
    @c36,
    @c37,
    @c38,
    @c39,
    @c40,
    @c41,
    @c42,
    @c43,
    @c44,
    @c45,
    @c46,
    @c47,
    @c48,
    @c49,
    @c50,
    @c51,
    @c52	) 
end