create procedure [sp_MSins_dboCandidate]
    @c1 int,
    @c2 int,
    @c3 int,
    @c4 datetime,
    @c5 nvarchar(50),
    @c6 nvarchar(50),
    @c7 nvarchar(50),
    @c8 nvarchar(50),
    @c9 nvarchar(50),
    @c10 nvarchar(50),
    @c11 int,
    @c12 nvarchar(8),
    @c13 int,
    @c14 decimal(13,10),
    @c15 decimal(13,10),
    @c16 int,
    @c17 int,
    @c18 nvarchar(10),
    @c19 int,
    @c20 bigint,
    @c21 int,
    @c22 int,
    @c23 int,
    @c24 nvarchar(50),
    @c25 bit,
    @c26 datetime,
    @c27 nvarchar(50),
    @c28 int,
    @c29 nvarchar(256),
    @c30 nvarchar(256),
    @c31 bit,
    @c32 bit,
    @c33 bit,
    @c34 nvarchar(100),
    @c35 bit,
    @c36 smallint,
    @c37 bit,
    @c38 bit,
    @c39 smallint,
    @c40 smallint,
    @c41 datetime,
    @c42 smallint,
    @c43 nvarchar(50),
    @c44 datetime,
    @c45 bit,
    @c46 bit,
    @c47 bit,
    @c48 bit
as
begin  
	insert into [dbo].[Candidate](
		[CandidateId],
		[PersonId],
		[CandidateStatusTypeId],
		[DateofBirth],
		[AddressLine1],
		[AddressLine2],
		[AddressLine3],
		[AddressLine4],
		[AddressLine5],
		[Town],
		[CountyId],
		[Postcode],
		[LocalAuthorityId],
		[Longitude],
		[Latitude],
		[GeocodeEasting],
		[GeocodeNorthing],
		[NiReference],
		[VoucherReferenceNumber],
		[UniqueLearnerNumber],
		[UlnStatusId],
		[Gender],
		[EthnicOrigin],
		[EthnicOriginOther],
		[ApplicationLimitEnforced],
		[LastAccessedDate],
		[AdditionalEmail],
		[Disability],
		[DisabilityOther],
		[HealthProblems],
		[ReceivePushedContent],
		[ReferralAgent],
		[DisableAlerts],
		[UnconfirmedEmailAddress],
		[MobileNumberUnconfirmed],
		[DoBFailureCount],
		[ForgottenUsernameRequested],
		[ForgottenPasswordRequested],
		[TextFailureCount],
		[EmailFailureCount],
		[LastAccessedManageApplications],
		[ReferralPoints],
		[BeingSupportedBy],
		[LockedForSupportUntil],
		[NewVacancyAlertEmail],
		[NewVacancyAlertSMS],
		[AllowMarketingMessages],
		[ReminderMessageSent]
	) values (
    @c1,
    @c2,
    @c3,
    @c4,
    @c5,
    @c6,
    @c7,
    @c8,
    @c9,
    @c10,
    @c11,
    @c12,
    @c13,
    @c14,
    @c15,
    @c16,
    @c17,
    @c18,
    @c19,
    @c20,
    @c21,
    @c22,
    @c23,
    @c24,
    @c25,
    @c26,
    @c27,
    @c28,
    @c29,
    @c30,
    @c31,
    @c32,
    @c33,
    @c34,
    @c35,
    @c36,
    @c37,
    @c38,
    @c39,
    @c40,
    @c41,
    @c42,
    @c43,
    @c44,
    @c45,
    @c46,
    @c47,
    @c48	) 
end