create procedure [sp_MSins_dboStakeHolder]
    @c1 int,
    @c2 int,
    @c3 int,
    @c4 nvarchar(50),
    @c5 nvarchar(50),
    @c6 nvarchar(50),
    @c7 nvarchar(50),
    @c8 nvarchar(50),
    @c9 nvarchar(50),
    @c10 int,
    @c11 nvarchar(100),
    @c12 nvarchar(8),
    @c13 int,
    @c14 nvarchar(50),
    @c15 decimal(13,10),
    @c16 decimal(13,10),
    @c17 int,
    @c18 int,
    @c19 datetime,
    @c20 bit,
    @c21 bit,
    @c22 bit,
    @c23 nvarchar(50),
    @c24 datetime,
    @c25 int
as
begin  
	insert into [dbo].[StakeHolder](
		[StakeHolderID],
		[PersonId],
		[StakeHolderStatusId],
		[AddressLine1],
		[AddressLine2],
		[AddressLine3],
		[AddressLine4],
		[AddressLine5],
		[Town],
		[CountyId],
		[UnconfirmedEmailAddress],
		[Postcode],
		[OrganisationId],
		[OrganisationOther],
		[Longitude],
		[Latitude],
		[GeocodeEasting],
		[GeocodeNorthing],
		[LastAccessedDate],
		[ForgottenUsernameRequested],
		[ForgottenPasswordRequested],
		[EmailAlertSent],
		[BeingSupportedBy],
		[LockedForSupportUntil],
		[LocalAuthorityId]
	) values (
    @c1,
    @c2,
    @c3,
    @c4,
    @c5,
    @c6,
    @c7,
    @c8,
    @c9,
    @c10,
    @c11,
    @c12,
    @c13,
    @c14,
    @c15,
    @c16,
    @c17,
    @c18,
    @c19,
    @c20,
    @c21,
    @c22,
    @c23,
    @c24,
    @c25	) 
end