create procedure [sp_MSins_dboEmployer]
    @c1 int,
    @c2 int,
    @c3 nvarchar(255),
    @c4 nvarchar(255),
    @c5 nvarchar(50),
    @c6 nvarchar(50),
    @c7 nvarchar(50),
    @c8 nvarchar(50),
    @c9 nvarchar(50),
    @c10 nvarchar(50),
    @c11 int,
    @c12 nvarchar(8),
    @c13 int,
    @c14 decimal(13,10),
    @c15 decimal(13,10),
    @c16 int,
    @c17 int,
    @c18 int,
    @c19 int,
    @c20 int,
    @c21 varchar(255),
    @c22 varchar(8),
    @c23 int,
    @c24 nvarchar(50),
    @c25 datetime,
    @c26 int,
    @c27 bit,
    @c28 bit
as
begin  
	insert into [dbo].[Employer](
		[EmployerId],
		[EdsUrn],
		[FullName],
		[TradingName],
		[AddressLine1],
		[AddressLine2],
		[AddressLine3],
		[AddressLine4],
		[AddressLine5],
		[Town],
		[CountyId],
		[PostCode],
		[LocalAuthorityId],
		[Longitude],
		[Latitude],
		[GeocodeEasting],
		[GeocodeNorthing],
		[PrimaryContact],
		[NumberofEmployeesAtSite],
		[NumberOfEmployeesInGroup],
		[OwnerOrgnistaion],
		[CompanyRegistrationNumber],
		[TotalVacanciesPosted],
		[BeingSupportedBy],
		[LockedForSupportUntil],
		[EmployerStatusTypeId],
		[DisableAllowed],
		[TrackingAllowed]
	) values (
    @c1,
    @c2,
    @c3,
    @c4,
    @c5,
    @c6,
    @c7,
    @c8,
    @c9,
    @c10,
    @c11,
    @c12,
    @c13,
    @c14,
    @c15,
    @c16,
    @c17,
    @c18,
    @c19,
    @c20,
    @c21,
    @c22,
    @c23,
    @c24,
    @c25,
    @c26,
    @c27,
    @c28	) 
end