create procedure [sp_MSupd_dboVacancySearch]
		@c1 int = NULL,
		@c2 int = NULL,
		@c3 int = NULL,
		@c4 nvarchar(256) = NULL,
		@c5 nvarchar(256) = NULL,
		@c6 nvarchar(256) = NULL,
		@c7 int = NULL,
		@c8 int = NULL,
		@c9 decimal(13,10) = NULL,
		@c10 decimal(13,10) = NULL,
		@c11 int = NULL,
		@c12 datetime = NULL,
		@c13 nvarchar(100) = NULL,
		@c14 nvarchar(256) = NULL,
		@c15 nvarchar(max) = NULL,
		@c16 int = NULL,
		@c17 datetime = NULL,
		@c18 int = NULL,
		@c19 nvarchar(200) = NULL,
		@c20 nvarchar(200) = NULL,
		@c21 int = NULL,
		@c22 money = NULL,
		@c23 int = NULL,
		@c24 nvarchar(40) = NULL,
		@c25 int = NULL,
		@c26 int = NULL,
		@c27 nvarchar(max) = NULL,
		@c28 nvarchar(max) = NULL,
		@c29 bit = NULL,
		@pkc1 int = NULL,
		@bitmap binary(4)
as
begin  
update [dbo].[VacancySearch] set
		[VacancyId] = case substring(@bitmap,1,1) & 2 when 2 then @c2 else [VacancyId] end,
		[VacancyReferenceNumber] = case substring(@bitmap,1,1) & 4 when 4 then @c3 else [VacancyReferenceNumber] end,
		[EmployerName] = case substring(@bitmap,1,1) & 8 when 8 then @c4 else [EmployerName] end,
		[VacancyOwnerName] = case substring(@bitmap,1,1) & 16 when 16 then @c5 else [VacancyOwnerName] end,
		[DeliveryOrganisationName] = case substring(@bitmap,1,1) & 32 when 32 then @c6 else [DeliveryOrganisationName] end,
		[GeocodeEasting] = case substring(@bitmap,1,1) & 64 when 64 then @c7 else [GeocodeEasting] end,
		[GeocodeNorthing] = case substring(@bitmap,1,1) & 128 when 128 then @c8 else [GeocodeNorthing] end,
		[Latitude] = case substring(@bitmap,2,1) & 1 when 1 then @c9 else [Latitude] end,
		[Longitude] = case substring(@bitmap,2,1) & 2 when 2 then @c10 else [Longitude] end,
		[LocalAuthorityID] = case substring(@bitmap,2,1) & 4 when 4 then @c11 else [LocalAuthorityID] end,
		[VacancyPostedDate] = case substring(@bitmap,2,1) & 8 when 8 then @c12 else [VacancyPostedDate] end,
		[Title] = case substring(@bitmap,2,1) & 16 when 16 then @c13 else [Title] end,
		[ShortDescription] = case substring(@bitmap,2,1) & 32 when 32 then @c14 else [ShortDescription] end,
		[Description] = case substring(@bitmap,2,1) & 64 when 64 then @c15 else [Description] end,
		[Status] = case substring(@bitmap,2,1) & 128 when 128 then @c16 else [Status] end,
		[ApplicationClosingDate] = case substring(@bitmap,3,1) & 1 when 1 then @c17 else [ApplicationClosingDate] end,
		[ApprenticeshipFrameworkId] = case substring(@bitmap,3,1) & 2 when 2 then @c18 else [ApprenticeshipFrameworkId] end,
		[ApprenticeshipOccupationName] = case substring(@bitmap,3,1) & 4 when 4 then @c19 else [ApprenticeshipOccupationName] end,
		[ApprenticeshipFrameworkName] = case substring(@bitmap,3,1) & 8 when 8 then @c20 else [ApprenticeshipFrameworkName] end,
		[CountyId] = case substring(@bitmap,3,1) & 16 when 16 then @c21 else [CountyId] end,
		[WeeklyWage] = case substring(@bitmap,3,1) & 32 when 32 then @c22 else [WeeklyWage] end,
		[WageType] = case substring(@bitmap,3,1) & 64 when 64 then @c23 else [WageType] end,
		[Town] = case substring(@bitmap,3,1) & 128 when 128 then @c24 else [Town] end,
		[ApprenticeshipType] = case substring(@bitmap,4,1) & 1 when 1 then @c25 else [ApprenticeshipType] end,
		[ApplicationClosingDateAsInt] = case substring(@bitmap,4,1) & 2 when 2 then @c26 else [ApplicationClosingDateAsInt] end,
		[RealityCheck] = case substring(@bitmap,4,1) & 4 when 4 then @c27 else [RealityCheck] end,
		[OtherImportantInformation] = case substring(@bitmap,4,1) & 8 when 8 then @c28 else [OtherImportantInformation] end,
		[NationalVacancy] = case substring(@bitmap,4,1) & 16 when 16 then @c29 else [NationalVacancy] end
where [VacancySearchId] = @pkc1
if @@rowcount = 0
    if @@microsoftversion>0x07320000
        exec sp_MSreplraiserror 20598
end