CREATE TABLE [dbo].[MasterUPIN] (
    [MasterUPINId] INT IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [UKPRN]        INT NOT NULL,
    [UPIN]         INT NOT NULL,
    CONSTRAINT [PK_MasterUPIN] PRIMARY KEY CLUSTERED ([MasterUPINId] ASC),
    CONSTRAINT [uq_idx_MasterUPIN] UNIQUE NONCLUSTERED ([UKPRN] ASC, [UPIN] ASC)
);

