CREATE TABLE [dbo].[MIMEType] (
    [MIMETypeId] INT            IDENTITY (-1, -1) NOT FOR REPLICATION NOT NULL,
    [CodeName]   NVARCHAR (3)   NOT NULL,
    [ShortName]  NVARCHAR (100) NOT NULL,
    [FullName]   NVARCHAR (200) NOT NULL,
    CONSTRAINT [PK_MIMEType] PRIMARY KEY CLUSTERED ([MIMETypeId] ASC),
    CONSTRAINT [uq_idx_MIMEType] UNIQUE NONCLUSTERED ([FullName] ASC)
);

