CREATE TABLE [dbo].[ProviderSite] (
    [ProviderSiteID]                     INT              IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [FullName]                           NVARCHAR (255)   COLLATE Latin1_General_CI_AS NOT NULL,
    [TradingName]                        NVARCHAR (255)   COLLATE Latin1_General_CI_AS NOT NULL,
    [EDSURN]                             INT              NOT NULL,
    [AddressLine1]                       NVARCHAR (50)    COLLATE Latin1_General_CI_AS NOT NULL,
    [AddressLine2]                       NVARCHAR (50)    COLLATE Latin1_General_CI_AS NULL,
    [AddressLine3]                       NVARCHAR (50)    COLLATE Latin1_General_CI_AS NULL,
    [AddressLine4]                       NVARCHAR (50)    COLLATE Latin1_General_CI_AS NULL,
    [AddressLine5]                       NVARCHAR (50)    COLLATE Latin1_General_CI_AS NULL,
    [Town]                               NVARCHAR (50)    COLLATE Latin1_General_CI_AS NOT NULL,
    [CountyId]                           INT              NOT NULL,
    [PostCode]                           NVARCHAR (8)     COLLATE Latin1_General_CI_AS NOT NULL,
    [LocalAuthorityId]                   INT              NULL,
    [ManagingAreaID]                     INT              NULL,
    [Longitude]                          DECIMAL (13, 10) NULL,
    [Latitude]                           DECIMAL (13, 10) NULL,
    [GeocodeEasting]                     INT              NULL,
    [GeocodeNorthing]                    INT              NULL,
    [OwnerOrganisation]                  NVARCHAR (255)   COLLATE Latin1_General_CI_AS NULL,
    [EmployerDescription]                NVARCHAR (MAX)   COLLATE Latin1_General_CI_AS NULL,
    [CandidateDescription]               NVARCHAR (MAX)   COLLATE Latin1_General_CI_AS NULL,
    [WebPage]                            NVARCHAR (100)   COLLATE Latin1_General_CI_AS NULL,
    [OutofDate]                          BIT              NOT NULL,
    [ContactDetailsForEmployer]          NVARCHAR (256)   COLLATE Latin1_General_CI_AS NULL,
    [ContactDetailsForCandidate]         NVARCHAR (256)   COLLATE Latin1_General_CI_AS NULL,
    [HideFromSearch]                     BIT              NOT NULL,
    [TrainingProviderStatusTypeId]       INT              NULL,
    [IsRecruitmentAgency]                BIT              CONSTRAINT [SiteProvider_IsRecruitmentAgency] DEFAULT ((0)) NOT NULL,
    [ContactDetailsAsARecruitmentAgency] NVARCHAR (1000)  COLLATE Latin1_General_CI_AS NULL,
    CONSTRAINT [PK_Training_Provider] PRIMARY KEY CLUSTERED ([ProviderSiteID] ASC),
    CONSTRAINT [FK_TrainingProvider_County] FOREIGN KEY ([CountyId]) REFERENCES [dbo].[County] ([CountyId]) NOT FOR REPLICATION,
    CONSTRAINT [FK_TrainingProvider_EmployerTrainingProviderStatus] FOREIGN KEY ([TrainingProviderStatusTypeId]) REFERENCES [dbo].[EmployerTrainingProviderStatus] ([EmployerTrainingProviderStatusId]) NOT FOR REPLICATION,
    CONSTRAINT [FK_TrainingProvider_LocalAuthority] FOREIGN KEY ([LocalAuthorityId]) REFERENCES [dbo].[LocalAuthority] ([LocalAuthorityId]) NOT FOR REPLICATION,
    CONSTRAINT [uq_idx_trainingProvider] UNIQUE NONCLUSTERED ([EDSURN] ASC)
);



