CREATE TABLE [dbo].[StakeHolder] (
    [StakeHolderID]              INT              IDENTITY (60000000, 1) NOT FOR REPLICATION NOT NULL,
    [PersonId]                   INT              NOT NULL,
    [StakeHolderStatusId]        INT              NOT NULL,
    [AddressLine1]               NVARCHAR (50)    COLLATE Latin1_General_CI_AS NOT NULL,
    [AddressLine2]               NVARCHAR (50)    COLLATE Latin1_General_CI_AS NULL,
    [AddressLine3]               NVARCHAR (50)    COLLATE Latin1_General_CI_AS NULL,
    [AddressLine4]               NVARCHAR (50)    COLLATE Latin1_General_CI_AS NULL,
    [AddressLine5]               NVARCHAR (50)    COLLATE Latin1_General_CI_AS NULL,
    [Town]                       NVARCHAR (50)    COLLATE Latin1_General_CI_AS NOT NULL,
    [CountyId]                   INT              NOT NULL,
    [UnconfirmedEmailAddress]    NVARCHAR (100)   COLLATE Latin1_General_CI_AS NULL,
    [Postcode]                   NVARCHAR (8)     COLLATE Latin1_General_CI_AS NOT NULL,
    [OrganisationId]             INT              NOT NULL,
    [OrganisationOther]          NVARCHAR (50)    COLLATE Latin1_General_CI_AS NULL,
    [Longitude]                  DECIMAL (13, 10) NULL,
    [Latitude]                   DECIMAL (13, 10) NULL,
    [GeocodeEasting]             INT              NULL,
    [GeocodeNorthing]            INT              NULL,
    [LastAccessedDate]           DATETIME         NULL,
    [ForgottenUsernameRequested] BIT              CONSTRAINT [DF_StakeHolder_ForgottenUsernameRequested] DEFAULT ((0)) NOT NULL,
    [ForgottenPasswordRequested] BIT              CONSTRAINT [DF_StakeHolder_ForgottenPasswordRequested] DEFAULT ((0)) NOT NULL,
    [EmailAlertSent]             BIT              CONSTRAINT [DF_StakeHolder_EmailAlertSent] DEFAULT ((0)) NOT NULL,
    [BeingSupportedBy]           NVARCHAR (50)    COLLATE Latin1_General_CI_AS NULL,
    [LockedForSupportUntil]      DATETIME         NULL,
    [LocalAuthorityId]           INT              NULL,
    CONSTRAINT [PK__StakeHolder__2F1AED73] PRIMARY KEY CLUSTERED ([StakeHolderID] ASC),
    CONSTRAINT [FK_StakeHolder_County] FOREIGN KEY ([CountyId]) REFERENCES [dbo].[County] ([CountyId]) NOT FOR REPLICATION,
    CONSTRAINT [FK_StakeHolder_LocalAuthority] FOREIGN KEY ([LocalAuthorityId]) REFERENCES [dbo].[LocalAuthority] ([LocalAuthorityId]) NOT FOR REPLICATION,
    CONSTRAINT [FK_StakeHolder_OrganisationId] FOREIGN KEY ([OrganisationId]) REFERENCES [dbo].[Organisation] ([OrganisationId]) NOT FOR REPLICATION,
    CONSTRAINT [FK_StakeHolder_Person] FOREIGN KEY ([PersonId]) REFERENCES [dbo].[Person] ([PersonId]) NOT FOR REPLICATION,
    CONSTRAINT [FK_StakeHolder_StakeHolderStatus] FOREIGN KEY ([StakeHolderStatusId]) REFERENCES [dbo].[StakeHolderStatus] ([StakeHolderStatusId]) NOT FOR REPLICATION
);



