#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.Apprenticeships.Web.Recruit.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SFA.Apprenticeships.Infrastructure.Presentation;
    using SFA.Apprenticeships.Web.Common.Constants;
    using SFA.Apprenticeships.Web.Common.Framework;
    using SFA.Apprenticeships.Web.Common.Models.Common;
    using SFA.Apprenticeships.Web.Raa.Common.Views.Shared.DisplayTemplates;
    using SFA.Apprenticeships.Web.Recruit;
    
    #line 1 "..\..\Views\Shared\_LoginPartial.cshtml"
    using SFA.Apprenticeships.Web.Recruit.Constants;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Shared\_LoginPartial.cshtml"
    using SFA.Apprenticeships.Web.Recruit.Controllers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_LoginPartial.cshtml")]
    public partial class LoginPartial : System.Web.Mvc.WebViewPage<dynamic>
    {
        public LoginPartial()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Shared\_LoginPartial.cshtml"
 if (Request.IsAuthenticated)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"account-info\"");

WriteLiteral(" id=\"bannerSignedIn\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"small-btm-margin\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" id=\"signout-link\"");

WriteAttribute("href", Tuple.Create(" href=\"", 262), Tuple.Create("\"", 313)
            
            #line 8 "..\..\Views\Shared\_LoginPartial.cshtml"
, Tuple.Create(Tuple.Create("", 269), Tuple.Create<System.Object, System.Int32>(Url.RouteUrl(RecruitmentRouteNames.SignOut)
            
            #line default
            #line hidden
, 269), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-sign-out\"");

WriteLiteral("></i>Sign out</a>\r\n        </div>\r\n");

            
            #line 10 "..\..\Views\Shared\_LoginPartial.cshtml"
        
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Shared\_LoginPartial.cshtml"
         if (User.IsInRole(SFA.Apprenticeships.Domain.Entities.Roles.VerifiedEmail))
        {

            
            #line default
            #line hidden
WriteLiteral("            <div>\r\n");

            
            #line 13 "..\..\Views\Shared\_LoginPartial.cshtml"
                
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Shared\_LoginPartial.cshtml"
                 if(Request.RawUrl != Url.RouteUrl(RecruitmentRouteNames.RecruitmentHome)) {

            
            #line default
            #line hidden
WriteLiteral("                    <a");

WriteLiteral(" class=\"account-link\"");

WriteLiteral(" id=\"applicationsLink\"");

WriteAttribute("href", Tuple.Create(" href=\"", 650), Tuple.Create("\"", 709)
            
            #line 14 "..\..\Views\Shared\_LoginPartial.cshtml"
, Tuple.Create(Tuple.Create("", 657), Tuple.Create<System.Object, System.Int32>(Url.RouteUrl(RecruitmentRouteNames.RecruitmentHome)
            
            #line default
            #line hidden
, 657), false)
);

WriteLiteral(">Home</a>\r\n");

            
            #line 15 "..\..\Views\Shared\_LoginPartial.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                \r\n                <!--<a class=\"account-link\" id=\"applicationsLin" +
"k\" href=\"");

            
            #line 17 "..\..\Views\Shared\_LoginPartial.cshtml"
                                                                   Write(Url.RouteUrl(RecruitmentRouteNames.ManageProviderSites));

            
            #line default
            #line hidden
WriteLiteral("\">Provider details</a>-->\r\n                <!--<a class=\"\" id=\"applicationsLink\" " +
"href=\"user-info.html\">Contact details</a>-->\r\n            </div>\r\n");

            
            #line 20 "..\..\Views\Shared\_LoginPartial.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");

            
            #line 22 "..\..\Views\Shared\_LoginPartial.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"account-info\"");

WriteLiteral(" id=\"bannerSignedOut\"");

WriteLiteral(">\r\n");

            
            #line 26 "..\..\Views\Shared\_LoginPartial.cshtml"
        
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Shared\_LoginPartial.cshtml"
         if (ViewBag.AllowReturnUrl != null && ViewBag.AllowReturnUrl && Request.Url != null)
        {

            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1241), Tuple.Create("\"", 1291)
            
            #line 28 "..\..\Views\Shared\_LoginPartial.cshtml"
, Tuple.Create(Tuple.Create("", 1248), Tuple.Create<System.Object, System.Int32>(Url.RouteUrl(RecruitmentRouteNames.SignIn)
            
            #line default
            #line hidden
, 1248), false)
);

WriteLiteral(" id=\"loginLink\"");

WriteLiteral(" title=\"Sign in / Create account\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-sign-in\"");

WriteLiteral("></i>Sign in / Create account</a>\r\n");

            
            #line 29 "..\..\Views\Shared\_LoginPartial.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1450), Tuple.Create("\"", 1500)
            
            #line 32 "..\..\Views\Shared\_LoginPartial.cshtml"
, Tuple.Create(Tuple.Create("", 1457), Tuple.Create<System.Object, System.Int32>(Url.RouteUrl(RecruitmentRouteNames.SignIn)
            
            #line default
            #line hidden
, 1457), false)
);

WriteLiteral(" id=\"loginLink\"");

WriteLiteral(" title=\"Sign in / Create account\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-sign-in\"");

WriteLiteral("></i>Sign in / Create account</a>\r\n");

            
            #line 33 "..\..\Views\Shared\_LoginPartial.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");

            
            #line 35 "..\..\Views\Shared\_LoginPartial.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
