#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.Apprenticeships.Web.Raa.Common.Views.Shared.DisplayTemplates.Vacancy
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
    using SFA.Apprenticeships.Domain.Entities.Vacancies;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
    using SFA.Apprenticeships.Domain.Entities.Vacancies.ProviderVacancies;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
    using SFA.Apprenticeships.Infrastructure.Presentation.Constants;
    
    #line default
    #line hidden
    using SFA.Apprenticeships.Web.Common.Constants;
    using SFA.Apprenticeships.Web.Common.Framework;
    using SFA.Apprenticeships.Web.Common.Models.Common;
    using SFA.Apprenticeships.Web.Raa.Common;
    
    #line 4 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
    using SFA.Apprenticeships.Web.Raa.Common.Extensions;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
    using SFA.Apprenticeships.Web.Raa.Common.ViewModels.Vacancy;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/Vacancy/_WorkingWeekAndWage.cshtml")]
    public partial class WorkingWeekAndWage : System.Web.Mvc.WebViewPage<VacancyViewModel>
    {
        public WorkingWeekAndWage()
        {
        }
        public override void Execute()
        {
            
            #line 8 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
  
    var editableItemClass = ViewData["editableItemClass"];

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteAttribute("class", Tuple.Create(" class=\"", 408), Tuple.Create("\"", 434)
            
            #line 12 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
, Tuple.Create(Tuple.Create("", 416), Tuple.Create<System.Object, System.Int32>(editableItemClass
            
            #line default
            #line hidden
, 416), false)
);

WriteLiteral(">\r\n    <h3");

WriteLiteral(" class=\"bold-small\"");

WriteLiteral(">\r\n");

            
            #line 14 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
        
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
         if (Model.VacancyType == VacancyType.Traineeship)
        {

            
            #line default
            #line hidden
WriteLiteral("            <span>Weekly hours</span>\r\n");

            
            #line 17 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <span>Working week</span>\r\n");

            
            #line 21 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
            
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
       Write(Html.Partial(ValidationResultViewModel.PartialView, Html.GetValidationResultViewModel(Model, m => m.VacancySummaryViewModel.WorkingWeek, ViewData.ModelState, Model.SummaryLink, Model.VacancySummaryViewModel.WorkingWeekComment)));

            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
                                                                                                                                                                                                                                                
        }

            
            #line default
            #line hidden
WriteLiteral("    </h3>\r\n    <p");

WriteLiteral(" id=\"vacancy-working-week\"");

WriteLiteral(" itemprop=\"workHours\"");

WriteLiteral(" class=\"preserve-formatting\"");

WriteLiteral(">");

            
            #line 24 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
                                                                             Write(Model.VacancySummaryViewModel.WorkingWeek);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 25 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
    
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
     if (Model.VacancyType == VacancyType.Apprenticeship)
    {

            
            #line default
            #line hidden
WriteLiteral("        <p>Total hours per week: ");

            
            #line 27 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
                            Write(Model.VacancySummaryViewModel.HoursPerWeek);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 28 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
        
            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
         if (Model.VacancySummaryViewModel.HoursPerWeek > 40)
        {

            
            #line default
            #line hidden
WriteLiteral("            <p>(the hours are based on the candidate being over 18)</p>\r\n");

            
            #line 31 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
        }
            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
         
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 33 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
Write(Html.Partial(EditLinkViewModel.PartialView, Html.GetEditLinkViewModel(Model, m => m.VacancySummaryViewModel.WorkingWeek, Model.SummaryLink, Model.VacancySummaryViewModel.WorkingWeekComment)));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n");

            
            #line 36 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
 if (Model.VacancyType == VacancyType.Apprenticeship)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 1632), Tuple.Create("\"", 1658)
            
            #line 38 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
, Tuple.Create(Tuple.Create("", 1640), Tuple.Create<System.Object, System.Int32>(editableItemClass
            
            #line default
            #line hidden
, 1640), false)
);

WriteLiteral(">\r\n        <h3");

WriteLiteral(" class=\"bold-small\"");

WriteLiteral(">\r\n");

            
            #line 40 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
            
            
            #line default
            #line hidden
            
            #line 40 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
             if (Model.VacancySummaryViewModel.WageType == WageType.Custom)
            {

            
            #line default
            #line hidden
WriteLiteral("                <span>\r\n");

WriteLiteral("                    ");

            
            #line 43 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
               Write(Model.VacancySummaryViewModel.WageUnitDisplayText);

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 44 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
               Write(Html.Partial(ValidationResultViewModel.PartialView, Html.GetValidationResultViewModel(Model, m => m.VacancySummaryViewModel.WageType, ViewData.ModelState, Model.SummaryLink, Model.VacancySummaryViewModel.WageComment)));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </span>\r\n");

            
            #line 46 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <span>\r\n                    Weekly wage\r\n");

WriteLiteral("                    ");

            
            #line 51 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
               Write(Html.Partial(ValidationResultViewModel.PartialView, Html.GetValidationResultViewModel(Model, m => m.VacancySummaryViewModel.WageType, ViewData.ModelState, Model.SummaryLink, Model.VacancySummaryViewModel.WageComment)));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </span>\r\n");

            
            #line 53 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </h3>\r\n        <p");

WriteLiteral(" id=\"vacancy-wage\"");

WriteLiteral(">");

            
            #line 55 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
                        Write(Model.VacancySummaryViewModel.WageDisplayText);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

WriteLiteral("        ");

            
            #line 56 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
   Write(Html.Partial(EditLinkViewModel.PartialView, Html.GetEditLinkViewModel(Model, m => m.VacancySummaryViewModel.WageType, Model.SummaryLink, Model.VacancySummaryViewModel.WageComment)));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 58 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"

    
            
            #line default
            #line hidden
            
            #line 59 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
     if (Model.VacancySummaryViewModel.WageType == WageType.ApprenticeshipMinimumWage)
    {

            
            #line default
            #line hidden
WriteLiteral("        <details>\r\n            <summary>Wages explained</summary>\r\n            <d" +
"iv");

WriteLiteral(" class=\"detail-content\"");

WriteLiteral(">\r\n                The current National Minimum Wage (NMW) for apprentices is £");

            
            #line 64 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
                                                                       Write(Wages.ApprenticeMinimumWage);

            
            #line default
            #line hidden
WriteLiteral(@" per hour.<br />
                This rate applies to apprentices aged 16 to 18 and those aged 19 or over who are in their first year.<br />
                Apprentices must be paid at least the NMW for their age if they're aged 19 or over and have completed their first year.
            </div>
        </details>
");

            
            #line 69 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
    }
            
            #line default
            #line hidden
            
            #line 69 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
     

    
            
            #line default
            #line hidden
            
            #line 71 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
     if (Model.VacancySummaryViewModel.WageType == WageType.NationalMinimumWage)
    {

            
            #line default
            #line hidden
WriteLiteral("        <details>\r\n            <summary>Wages explained</summary>\r\n            <d" +
"iv");

WriteLiteral(" class=\"detail-content\"");

WriteLiteral(">\r\n                The current National Minimum Wage rates are £");

            
            #line 76 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
                                                        Write(Wages.Between18And20NationalMinimumWage);

            
            #line default
            #line hidden
WriteLiteral(" for 18 to 20 year-olds and £");

            
            #line 76 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
                                                                                                                             Write(Wages.Over21NationalMinimumWage);

            
            #line default
            #line hidden
WriteLiteral(" for anyone aged 21 and over.<br />\r\n                Apprentices are paid for the" +
"ir normal working hours and training that’s part of their apprenticeship (usuall" +
"y one day per week).\r\n            </div>\r\n        </details>\r\n");

            
            #line 80 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
    }
            
            #line default
            #line hidden
            
            #line 80 "..\..\Views\Shared\DisplayTemplates\Vacancy\_WorkingWeekAndWage.cshtml"
     
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
