$(function() {
  var jobTitle = [
    // "Applications Engineer",
    // "Applications Engineer (Senior)",
    // "Applications Engineer (Lead)",
    // "Applications Engineering Director",
    // "Applications Engineering Manager",
    // "Automation Director",
    // "CAD Designer",
    // "CAD Designer (Senior)",
    // "CAD Draftsperson",
    // "CAD Manager",
    // "CAD Supervisor",
    // "Chemical Engineer",
    // "Chemical Engineer (Senior)",
    // "Chemical Engineer (Lead)",
    // "Chemical Engineering Manager",
    // "Civil Engineer ",
    // "Civil Engineer (Senior)",
    // "Civil Engineer (Lead)",
    // "Civil Engineering Manager",
    // "Design Engineer ",
    // "Design Engineer (Senior)",
    // "Design Engineer (Lead)",
    // "Design Manager",
    // "Electrical Engineer ",
    // "Electrical Engineer (Senior)",
    // "Electrical Engineer (Lead)",
    // "Electrical Engineering Manager",
    // "Engineering Director",
    // "Engineering Manager",
    // "Engineering Supervisor",
    // "Engineering Technician",
    // "Industrial Engineer ",
    // "Industrial Engineer (Senior)",
    // "Industrial Engineer (Lead)",
    // "Industrial Engineering Manager",
    // "Manufacturing Engineer ",
    // "Manufacturing Engineer (Senior)",
    // "Manufacturing Engineer (Lead)",
    // "Manufacturing Engineering Manager",
    // "Mechanical Engineer ",
    // "Mechanical Engineer (Senior)",
    // "Mechanical Engineer (Lead)",
    // "Mechanical Engineering Manager",
    // "Packaging Engineer",
    // "Plant Engineer",
    // "Plant Engineering Manager",
    // "Process Engineer ",
    // "Process Engineer (Senior)",
    // "Process Engineer (Lead)",
    // "Process Engineering Manager",
    // "Product Designer",
    // "Product Engineering ",
    // "Product Engineer (Senior)",
    // "Product Engineer (Lead)",
    // "Quality Control Engineer ",
    // "Quality Control Engineer (Senior)",
    // "Quality Control Engineer (Lead)",
    // "Systems Engineer ",
    // "Systems Engineer (Senior)",
    // "Systems Engineer (Lead)",
    // "Systems Engineering Manager",
    // "Test Engineer ",
    // "Test Engineer (Senior)",
    // "Test Engineer (Lead)",
    // "Test Engineering Manager"
    "Hairdresser",
    "Junior Stylist"
  ];

  $( "#jobTitle" ).autocomplete({
      source: jobTitle
    });
})
