#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.Apprenticeships.Web.Manage.Views.Vacancy
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Vacancy\BasicDetails.cshtml"
    using SFA.Apprenticeships.Domain.Entities.Vacancies.ProviderVacancies;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Vacancy\BasicDetails.cshtml"
    using SFA.Apprenticeships.Domain.Entities.Vacancies.ProviderVacancies.Apprenticeship;
    
    #line default
    #line hidden
    using SFA.Apprenticeships.Infrastructure.Presentation;
    using SFA.Apprenticeships.Web.Common.Constants;
    using SFA.Apprenticeships.Web.Common.Framework;
    using SFA.Apprenticeships.Web.Common.Models.Common;
    using SFA.Apprenticeships.Web.Manage;
    
    #line 4 "..\..\Views\Vacancy\BasicDetails.cshtml"
    using SFA.Apprenticeships.Web.Manage.Constants;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Vacancy\BasicDetails.cshtml"
    using SFA.Apprenticeships.Web.Raa.Common.Extensions;
    
    #line default
    #line hidden
    using SFA.Apprenticeships.Web.Raa.Common.Views.Shared.DisplayTemplates;
    using SFA.Apprenticeships.Web.Raa.Common.Views.Shared.EditorTemplates;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Vacancy/BasicDetails.cshtml")]
    public partial class BasicDetails : System.Web.Mvc.WebViewPage<SFA.Apprenticeships.Web.Raa.Common.ViewModels.Vacancy.NewVacancyViewModel>
    {
        public BasicDetails()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Views\Vacancy\BasicDetails.cshtml"
  
    ViewBag.Title = "Recruit an Apprentice - Select framework and level";

    const string selected = "selected";

    var isApplicationThroughRAAYes = (Model.OfflineVacancy.HasValue && !Model.OfflineVacancy.Value) ? selected : null;
    var isApplicationThroughRAANo = (Model.OfflineVacancy.HasValue && Model.OfflineVacancy.Value) ? selected : null;

    var frameworksSelected = Model.TrainingType == TrainingType.Frameworks ? selected : null;
    var standardsSelected = Model.TrainingType == TrainingType.Standards ? selected : null;

    var isFramework = Model.TrainingType == TrainingType.Frameworks;
    var isStandard = Model.TrainingType == TrainingType.Standards;
    var frameworkClass = isFramework ? "" : "hide-nojs";
    var standardClass = isStandard ? "" : "hide-nojs";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h1");

WriteLiteral(" class=\"heading-xlarge\"");

WriteLiteral(">\r\n    Enter basic vacancy details\r\n</h1>\r\n\r\n");

            
            #line 27 "..\..\Views\Vacancy\BasicDetails.cshtml"
 using (Html.BeginRouteForm(ManagementRouteNames.BasicDetails, FormMethod.Post))
{
    
            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\Vacancy\BasicDetails.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\Vacancy\BasicDetails.cshtml"
                            
    
            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\Vacancy\BasicDetails.cshtml"
Write(Html.Partial("ValidationSummary", ViewData.ModelState));

            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\Vacancy\BasicDetails.cshtml"
                                                           

    
            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\Vacancy\BasicDetails.cshtml"
Write(Html.FormTextAreaFor(m => m.Title, controlHtmlAttributes: new { type = "text", size = 12, @class = "width-all-1-1 form-textarea-small" }));

            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\Vacancy\BasicDetails.cshtml"
                                                                                                                                              
    
            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\Vacancy\BasicDetails.cshtml"
Write(Html.EditorFor(m => m.TitleComment, "Comment", Html.GetLabelFor(m => m.TitleComment)));

            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\Vacancy\BasicDetails.cshtml"
                                                                                          
    
            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\Vacancy\BasicDetails.cshtml"
Write(Html.ValidationMessageFor(m => m.TitleComment));

            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\Vacancy\BasicDetails.cshtml"
                                                   

    
            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\Vacancy\BasicDetails.cshtml"
Write(Html.FormTextAreaFor(m => m.ShortDescription, controlHtmlAttributes: new { type = "text", size = 12, @class = "width-all-1-1 form-textarea-medium" }));

            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\Vacancy\BasicDetails.cshtml"
                                                                                                                                                          
    
            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\Vacancy\BasicDetails.cshtml"
Write(Html.EditorFor(m => m.ShortDescriptionComment, "Comment", Html.GetLabelFor(m => m.ShortDescriptionComment)));

            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\Vacancy\BasicDetails.cshtml"
                                                                                                                
    
            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\Vacancy\BasicDetails.cshtml"
Write(Html.ValidationMessageFor(m => m.ShortDescriptionComment));

            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\Vacancy\BasicDetails.cshtml"
                                                              


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"blocklabel-single-container\"");

WriteLiteral(">\r\n            <div");

WriteAttribute("class", Tuple.Create(" class=\"", 2128), Tuple.Create("\"", 2316)
, Tuple.Create(Tuple.Create("", 2136), Tuple.Create("form-group", 2136), true)
            
            #line 42 "..\..\Views\Vacancy\BasicDetails.cshtml"
, Tuple.Create(Tuple.Create(" ", 2146), Tuple.Create<System.Object, System.Int32>(SFA.Apprenticeships.Web.Common.Framework.HtmlExtensions.GetValidationCssClass(Html.GetValidationType(m => m.TrainingType))
            
            #line default
            #line hidden
, 2147), false)
, Tuple.Create(Tuple.Create(" ", 2272), Tuple.Create("inline", 2273), true)
, Tuple.Create(Tuple.Create(" ", 2279), Tuple.Create("clearfix", 2280), true)
, Tuple.Create(Tuple.Create(" ", 2288), Tuple.Create("blocklabel-single", 2289), true)
, Tuple.Create(Tuple.Create(" ", 2306), Tuple.Create("hide-nojs", 2307), true)
);

WriteLiteral(">\r\n                <a");

WriteAttribute("name", Tuple.Create(" name=\"", 2338), Tuple.Create("\"", 2400)
            
            #line 43 "..\..\Views\Vacancy\BasicDetails.cshtml"
, Tuple.Create(Tuple.Create("", 2345), Tuple.Create<System.Object, System.Int32>(Html.NameFor(m => m.TrainingType).ToString().ToLower()
            
            #line default
            #line hidden
, 2345), false)
);

WriteLiteral("></a>\r\n                <label");

WriteLiteral(" class=\"form-label\"");

WriteLiteral(">Apprenticeship type</label>\r\n                ");

WriteLiteral("\r\n                <label");

WriteLiteral(" data-target=\"training-type-frameworks-panel\"");

WriteLiteral(" for=\"training-type-frameworks\"");

WriteAttribute("class", Tuple.Create(" class=\"", 2642), Tuple.Create("\"", 2681)
, Tuple.Create(Tuple.Create("", 2650), Tuple.Create("block-label", 2650), true)
            
            #line 46 "..\..\Views\Vacancy\BasicDetails.cshtml"
                                     , Tuple.Create(Tuple.Create(" ", 2661), Tuple.Create<System.Object, System.Int32>(frameworksSelected
            
            #line default
            #line hidden
, 2662), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 47 "..\..\Views\Vacancy\BasicDetails.cshtml"
               Write(Html.RadioButtonFor(model => model.TrainingType, TrainingType.Frameworks, new {id = "training-type-frameworks", aria_controls = "training-type-frameworks-panel"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    Frameworks\r\n                </label>\r\n                ");

WriteLiteral("\r\n                <label");

WriteLiteral(" data-target=\"training-type-standards-panel\"");

WriteLiteral(" for=\"training-type-standards\"");

WriteAttribute("class", Tuple.Create(" class=\"", 3089), Tuple.Create("\"", 3127)
, Tuple.Create(Tuple.Create("", 3097), Tuple.Create("block-label", 3097), true)
            
            #line 51 "..\..\Views\Vacancy\BasicDetails.cshtml"
                                   , Tuple.Create(Tuple.Create(" ", 3108), Tuple.Create<System.Object, System.Int32>(standardsSelected
            
            #line default
            #line hidden
, 3109), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 52 "..\..\Views\Vacancy\BasicDetails.cshtml"
               Write(Html.RadioButtonFor(model => model.TrainingType, TrainingType.Standards, new {id = "training-type-standards", aria_controls = "training-type-standards-panel"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    Standards\r\n                </label>\r\n");

WriteLiteral("                ");

            
            #line 55 "..\..\Views\Vacancy\BasicDetails.cshtml"
           Write(Html.ValidationMessageFor(m => m.TrainingType));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n\r\n            <noscript>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <h3");

WriteLiteral(" class=\"bold-small\"");

WriteLiteral(">Apprenticeship type</h3>\r\n");

            
            #line 61 "..\..\Views\Vacancy\BasicDetails.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 61 "..\..\Views\Vacancy\BasicDetails.cshtml"
                     if (isFramework)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <label");

WriteLiteral(" class=\"unselected-apprenticeship-type\"");

WriteLiteral(">Framework</label>\r\n");

            
            #line 64 "..\..\Views\Vacancy\BasicDetails.cshtml"
                    }
                    else
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <button");

WriteLiteral(" id=\"selectFramework\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"button-link\"");

WriteLiteral(" name=\"BasicDetails\"");

WriteLiteral(" value=\"SelectFramework\"");

WriteLiteral(">Framework</button>\r\n");

            
            #line 68 "..\..\Views\Vacancy\BasicDetails.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 70 "..\..\Views\Vacancy\BasicDetails.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 70 "..\..\Views\Vacancy\BasicDetails.cshtml"
                     if (isStandard)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <label");

WriteLiteral(" class=\"unselected-apprenticeship-type\"");

WriteLiteral(">Standard</label>\r\n");

            
            #line 73 "..\..\Views\Vacancy\BasicDetails.cshtml"
                    }
                    else
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <button");

WriteLiteral(" id=\"selectStandard\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"button-link\"");

WriteLiteral(" name=\"BasicDetails\"");

WriteLiteral(" value=\"SelectStandard\"");

WriteLiteral(">Standard</button>\r\n");

            
            #line 77 "..\..\Views\Vacancy\BasicDetails.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n            </noscript>\r\n\r\n            <div");

WriteLiteral(" id=\"training-type-frameworks-panel\"");

WriteAttribute("class", Tuple.Create(" class=\"", 4486), Tuple.Create("\"", 4543)
, Tuple.Create(Tuple.Create("", 4494), Tuple.Create("toggle-content", 4494), true)
, Tuple.Create(Tuple.Create(" ", 4508), Tuple.Create("blocklabel-content", 4509), true)
            
            #line 81 "..\..\Views\Vacancy\BasicDetails.cshtml"
             , Tuple.Create(Tuple.Create(" ", 4527), Tuple.Create<System.Object, System.Int32>(frameworkClass
            
            #line default
            #line hidden
, 4528), false)
);

WriteLiteral(">\r\n                <div");

WriteAttribute("class", Tuple.Create(" class=\"", 4567), Tuple.Create("\"", 4716)
, Tuple.Create(Tuple.Create("", 4575), Tuple.Create("form-group", 4575), true)
            
            #line 82 "..\..\Views\Vacancy\BasicDetails.cshtml"
, Tuple.Create(Tuple.Create(" ", 4585), Tuple.Create<System.Object, System.Int32>(SFA.Apprenticeships.Web.Common.Framework.HtmlExtensions.GetValidationCssClass(Html.GetValidationType(m => m.FrameworkCodeName))
            
            #line default
            #line hidden
, 4586), false)
);

WriteLiteral(">\r\n                    <a");

WriteAttribute("name", Tuple.Create(" name=\"", 4742), Tuple.Create("\"", 4809)
            
            #line 83 "..\..\Views\Vacancy\BasicDetails.cshtml"
, Tuple.Create(Tuple.Create("", 4749), Tuple.Create<System.Object, System.Int32>(Html.NameFor(m => m.FrameworkCodeName).ToString().ToLower()
            
            #line default
            #line hidden
, 4749), false)
);

WriteLiteral("></a>\r\n                    <label");

WriteAttribute("for", Tuple.Create(" for=\"", 4843), Tuple.Create("\"", 4888)
            
            #line 84 "..\..\Views\Vacancy\BasicDetails.cshtml"
, Tuple.Create(Tuple.Create("", 4849), Tuple.Create<System.Object, System.Int32>(Html.NameFor(m => m.FrameworkCodeName)
            
            #line default
            #line hidden
, 4849), false)
);

WriteLiteral(" class=\"form-label\"");

WriteLiteral(">Apprenticeship framework</label>\r\n");

WriteLiteral("                    ");

            
            #line 85 "..\..\Views\Vacancy\BasicDetails.cshtml"
               Write(Html.DropDownListFor(m => m.FrameworkCodeName, Model.SectorsAndFrameworks, new {@class = "para-btm-margin chosen-select", style = "min-width: 50%;"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 86 "..\..\Views\Vacancy\BasicDetails.cshtml"
               Write(Html.ValidationMessageFor(m => m.FrameworkCodeName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 87 "..\..\Views\Vacancy\BasicDetails.cshtml"
               Write(Html.EditorFor(m => m.FrameworkCodeNameComment, "Comment", Html.GetLabelFor(m => m.FrameworkCodeNameComment)));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 88 "..\..\Views\Vacancy\BasicDetails.cshtml"
               Write(Html.ValidationMessageFor(m => m.FrameworkCodeNameComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n\r\n                <div");

WriteAttribute("class", Tuple.Create(" class=\"", 5448), Tuple.Create("\"", 5599)
, Tuple.Create(Tuple.Create("", 5456), Tuple.Create("form-group", 5456), true)
            
            #line 91 "..\..\Views\Vacancy\BasicDetails.cshtml"
, Tuple.Create(Tuple.Create(" ", 5466), Tuple.Create<System.Object, System.Int32>(SFA.Apprenticeships.Web.Common.Framework.HtmlExtensions.GetValidationCssClass(Html.GetValidationType(m => m.ApprenticeshipLevel))
            
            #line default
            #line hidden
, 5467), false)
);

WriteLiteral(">\r\n                    <a");

WriteAttribute("name", Tuple.Create(" name=\"", 5625), Tuple.Create("\"", 5694)
            
            #line 92 "..\..\Views\Vacancy\BasicDetails.cshtml"
, Tuple.Create(Tuple.Create("", 5632), Tuple.Create<System.Object, System.Int32>(Html.NameFor(m => m.ApprenticeshipLevel).ToString().ToLower()
            
            #line default
            #line hidden
, 5632), false)
);

WriteLiteral("></a>\r\n                    <label");

WriteLiteral(" class=\"form-label\"");

WriteLiteral(">Apprenticeship level</label>\r\n                        ");

WriteLiteral("\r\n                        <label");

WriteLiteral(" for=\"apprenticeship-level-intermediate\"");

WriteLiteral(" class=\"block-label\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 96 "..\..\Views\Vacancy\BasicDetails.cshtml"
                       Write(Html.RadioButtonFor(model => model.ApprenticeshipLevel, ApprenticeshipLevel.Intermediate, new {id = "apprenticeship-level-intermediate", aria_labelledby = "apprenticeship-level-label"}));

            
            #line default
            #line hidden
WriteLiteral(" Intermediate\r\n                        </label>\r\n\r\n                        ");

WriteLiteral("\r\n                        <label");

WriteLiteral(" for=\"apprenticeship-level-advanced\"");

WriteLiteral(" class=\"block-label\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 101 "..\..\Views\Vacancy\BasicDetails.cshtml"
                       Write(Html.RadioButtonFor(model => model.ApprenticeshipLevel, ApprenticeshipLevel.Advanced, new {id = "apprenticeship-level-advanced", aria_labelledby = "apprenticeship-level-label"}));

            
            #line default
            #line hidden
WriteLiteral(" Advanced\r\n                        </label>\r\n\r\n                        ");

WriteLiteral("\r\n                        <label");

WriteLiteral(" for=\"apprenticeship-level-higher\"");

WriteLiteral(" class=\"block-label\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 106 "..\..\Views\Vacancy\BasicDetails.cshtml"
                       Write(Html.RadioButtonFor(model => model.ApprenticeshipLevel, ApprenticeshipLevel.Higher, new {id = "apprenticeship-level-higher", aria_labelledby = "apprenticeship-level-label"}));

            
            #line default
            #line hidden
WriteLiteral(" Higher\r\n                        </label>\r\n\r\n                        ");

WriteLiteral("\r\n                        <label");

WriteLiteral(" for=\"apprenticeship-level-degree\"");

WriteLiteral(" class=\"block-label\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 111 "..\..\Views\Vacancy\BasicDetails.cshtml"
                       Write(Html.RadioButtonFor(model => model.ApprenticeshipLevel, ApprenticeshipLevel.Degree, new {id = "apprenticeship-level-degree", aria_labelledby = "apprenticeship-level-label"}));

            
            #line default
            #line hidden
WriteLiteral(" Degree\r\n                        </label>\r\n");

WriteLiteral("                    ");

            
            #line 113 "..\..\Views\Vacancy\BasicDetails.cshtml"
               Write(Html.ValidationMessageFor(m => m.ApprenticeshipLevel));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 114 "..\..\Views\Vacancy\BasicDetails.cshtml"
               Write(Html.EditorFor(m => m.ApprenticeshipLevelComment, "Comment", Html.GetLabelFor(m => m.ApprenticeshipLevelComment)));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 115 "..\..\Views\Vacancy\BasicDetails.cshtml"
               Write(Html.ValidationMessageFor(m => m.ApprenticeshipLevelComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" id=\"training-type-standards-panel\"");

WriteAttribute("class", Tuple.Create(" class=\"", 7828), Tuple.Create("\"", 7884)
, Tuple.Create(Tuple.Create("", 7836), Tuple.Create("toggle-content", 7836), true)
, Tuple.Create(Tuple.Create(" ", 7850), Tuple.Create("blocklabel-content", 7851), true)
            
            #line 119 "..\..\Views\Vacancy\BasicDetails.cshtml"
            , Tuple.Create(Tuple.Create(" ", 7869), Tuple.Create<System.Object, System.Int32>(standardClass
            
            #line default
            #line hidden
, 7870), false)
);

WriteLiteral(">\r\n                <div");

WriteAttribute("class", Tuple.Create(" class=\"", 7908), Tuple.Create("\"", 8050)
, Tuple.Create(Tuple.Create("", 7916), Tuple.Create("form-group", 7916), true)
            
            #line 120 "..\..\Views\Vacancy\BasicDetails.cshtml"
, Tuple.Create(Tuple.Create(" ", 7926), Tuple.Create<System.Object, System.Int32>(SFA.Apprenticeships.Web.Common.Framework.HtmlExtensions.GetValidationCssClass(Html.GetValidationType(m => m.StandardId))
            
            #line default
            #line hidden
, 7927), false)
);

WriteLiteral(">\r\n                    <a");

WriteAttribute("name", Tuple.Create(" name=\"", 8076), Tuple.Create("\"", 8136)
            
            #line 121 "..\..\Views\Vacancy\BasicDetails.cshtml"
, Tuple.Create(Tuple.Create("", 8083), Tuple.Create<System.Object, System.Int32>(Html.NameFor(m => m.StandardId).ToString().ToLower()
            
            #line default
            #line hidden
, 8083), false)
);

WriteLiteral("></a>\r\n                    <label");

WriteAttribute("for", Tuple.Create(" for=\"", 8170), Tuple.Create("\"", 8208)
            
            #line 122 "..\..\Views\Vacancy\BasicDetails.cshtml"
, Tuple.Create(Tuple.Create("", 8176), Tuple.Create<System.Object, System.Int32>(Html.NameFor(m => m.StandardId)
            
            #line default
            #line hidden
, 8176), false)
);

WriteLiteral(" class=\"form-label\"");

WriteLiteral(">Apprenticeship standard</label>\r\n                    <select");

WriteAttribute("name", Tuple.Create(" name=\"", 8289), Tuple.Create("\"", 8328)
            
            #line 123 "..\..\Views\Vacancy\BasicDetails.cshtml"
, Tuple.Create(Tuple.Create("", 8296), Tuple.Create<System.Object, System.Int32>(Html.NameFor(m => m.StandardId)
            
            #line default
            #line hidden
, 8296), false)
);

WriteAttribute("id", Tuple.Create(" id=\"", 8329), Tuple.Create("\"", 8366)
            
            #line 123 "..\..\Views\Vacancy\BasicDetails.cshtml"
, Tuple.Create(Tuple.Create("", 8334), Tuple.Create<System.Object, System.Int32>(Html.NameFor(m => m.StandardId)
            
            #line default
            #line hidden
, 8334), false)
);

WriteLiteral(" class=\"para-btm-margin chosen-select\"");

WriteLiteral(" style=\"min-width: 50%;\"");

WriteLiteral(">\r\n                        <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">Choose from the list of standards</option>\r\n");

            
            #line 125 "..\..\Views\Vacancy\BasicDetails.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 125 "..\..\Views\Vacancy\BasicDetails.cshtml"
                         foreach (var standardGroup in Model.Standards.GroupBy(s => s.Sector))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <optgroup");

WriteAttribute("label", Tuple.Create(" label=\"", 8677), Tuple.Create("\"", 8703)
            
            #line 127 "..\..\Views\Vacancy\BasicDetails.cshtml"
, Tuple.Create(Tuple.Create("", 8685), Tuple.Create<System.Object, System.Int32>(standardGroup.Key
            
            #line default
            #line hidden
, 8685), false)
);

WriteLiteral(">\r\n");

            
            #line 128 "..\..\Views\Vacancy\BasicDetails.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 128 "..\..\Views\Vacancy\BasicDetails.cshtml"
                                 foreach (var standard in standardGroup)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 8859), Tuple.Create("\"", 8879)
            
            #line 130 "..\..\Views\Vacancy\BasicDetails.cshtml"
, Tuple.Create(Tuple.Create("", 8867), Tuple.Create<System.Object, System.Int32>(standard.Id
            
            #line default
            #line hidden
, 8867), false)
);

WriteLiteral(" ");

            
            #line 130 "..\..\Views\Vacancy\BasicDetails.cshtml"
                                                             Write(standard.Id == Model.StandardId ? "selected" : "");

            
            #line default
            #line hidden
WriteLiteral(" data-apprenticeship-level=\"");

            
            #line 130 "..\..\Views\Vacancy\BasicDetails.cshtml"
                                                                                                                                            Write(standard.ApprenticeshipLevel);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n");

WriteLiteral("                                        ");

            
            #line 131 "..\..\Views\Vacancy\BasicDetails.cshtml"
                                   Write(standard.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </option>\r\n");

            
            #line 133 "..\..\Views\Vacancy\BasicDetails.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </optgroup>\r\n");

            
            #line 135 "..\..\Views\Vacancy\BasicDetails.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </select>\r\n\r\n");

WriteLiteral("                    ");

            
            #line 138 "..\..\Views\Vacancy\BasicDetails.cshtml"
               Write(Html.ValidationMessageFor(m => m.StandardId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 139 "..\..\Views\Vacancy\BasicDetails.cshtml"
               Write(Html.EditorFor(m => m.StandardIdComment, "Comment", Html.GetLabelFor(m => m.StandardIdComment)));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 140 "..\..\Views\Vacancy\BasicDetails.cshtml"
               Write(Html.ValidationMessageFor(m => m.StandardIdComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"form-group hide-nojs\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"form-label\"");

WriteLiteral(">Apprenticeship level</label>\r\n                    <p");

WriteLiteral(" id=\"apprenticeship-level-name\"");

WriteLiteral(">");

            
            #line 145 "..\..\Views\Vacancy\BasicDetails.cshtml"
                                                 Write(Html.DisplayFor(m => m.ApprenticeshipLevel));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 150 "..\..\Views\Vacancy\BasicDetails.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"blocklabel-single-container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group inline clearfix blocklabel-single hide-nojs\"");

WriteLiteral(">\r\n                <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral(">Manage application method</h3>\r\n                <p>\r\n                    Will th" +
"is vacancy be managed through the find an apprentice\r\n                    site?\r" +
"\n                </p>\r\n                ");

WriteLiteral("\r\n                <label");

WriteLiteral(" for=\"apprenticeship-online-vacancy\"");

WriteLiteral(" class=\"block-label\"");

WriteLiteral(" data-target=\"online-panel\"");

WriteLiteral(" ");

            
            #line 160 "..\..\Views\Vacancy\BasicDetails.cshtml"
                                                                                                     Write(isApplicationThroughRAAYes);

            
            #line default
            #line hidden
WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 161 "..\..\Views\Vacancy\BasicDetails.cshtml"
               Write(Html.RadioButtonFor(model => model.OfflineVacancy, false, new { id = "apprenticeship-online-vacancy", aria_labelledby = "apprenticeship-vacancy-management-type-label" }));

            
            #line default
            #line hidden
WriteLiteral(" Yes\r\n                </label>\r\n\r\n                ");

WriteLiteral("\r\n                <label");

WriteLiteral(" for=\"apprenticeship-offline-vacancy\"");

WriteLiteral(" class=\"block-label\"");

WriteLiteral(" data-target=\"offline-panel\"");

WriteLiteral(" ");

            
            #line 165 "..\..\Views\Vacancy\BasicDetails.cshtml"
                                                                                                       Write(isApplicationThroughRAANo);

            
            #line default
            #line hidden
WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 166 "..\..\Views\Vacancy\BasicDetails.cshtml"
               Write(Html.RadioButtonFor(model => model.OfflineVacancy, true, new { id = "apprenticeship-offline-vacancy", aria_labelledby = "apprenticeship-vacancy-management-type-label", aria_controls = "offline-panel" }));

            
            #line default
            #line hidden
WriteLiteral(" No\r\n                </label>\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"offline-panel\"");

WriteLiteral(" class=\"toggle-content panel-indent blocklabel-content\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 172 "..\..\Views\Vacancy\BasicDetails.cshtml"
               Write(Html.FormTextFor(m => m.OfflineApplicationUrl, controlHtmlAttributes: new { @class = "width-all-1-1", type = "text", size = 12, id = "apprenticeship-offline-application-url" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 173 "..\..\Views\Vacancy\BasicDetails.cshtml"
               Write(Html.EditorFor(m => m.OfflineApplicationUrlComment, "Comment", Html.GetLabelFor(m => m.OfflineApplicationUrlComment)));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 174 "..\..\Views\Vacancy\BasicDetails.cshtml"
               Write(Html.ValidationMessageFor(m => m.OfflineApplicationUrlComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 178 "..\..\Views\Vacancy\BasicDetails.cshtml"
               Write(Html.FormTextAreaFor(m => m.OfflineApplicationInstructions, controlHtmlAttributes: new { type = "text", size = 12, @class = "width-all-1-1 form-textarea-medium", id = "apprenticheship-offline-application-instructions" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 179 "..\..\Views\Vacancy\BasicDetails.cshtml"
               Write(Html.EditorFor(m => m.OfflineApplicationInstructionsComment, "Comment", Html.GetLabelFor(m => m.OfflineApplicationInstructionsComment)));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 180 "..\..\Views\Vacancy\BasicDetails.cshtml"
               Write(Html.ValidationMessageFor(m => m.OfflineApplicationInstructionsComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <br />\r\n                </div>\r\n            </div>\r\n       " +
" </div>\r\n    </div>\r\n");

            
            #line 186 "..\..\Views\Vacancy\BasicDetails.cshtml"

    
            
            #line default
            #line hidden
            
            #line 187 "..\..\Views\Vacancy\BasicDetails.cshtml"
Write(Html.HiddenFor(model => model.VacancyReferenceNumber));

            
            #line default
            #line hidden
            
            #line 187 "..\..\Views\Vacancy\BasicDetails.cshtml"
                                                          
    
            
            #line default
            #line hidden
            
            #line 188 "..\..\Views\Vacancy\BasicDetails.cshtml"
Write(Html.HiddenFor(model => model.Ukprn));

            
            #line default
            #line hidden
            
            #line 188 "..\..\Views\Vacancy\BasicDetails.cshtml"
                                         
    
            
            #line default
            #line hidden
            
            #line 189 "..\..\Views\Vacancy\BasicDetails.cshtml"
Write(Html.HiddenFor(model => model.ProviderSiteEmployerLink.ProviderSiteErn));

            
            #line default
            #line hidden
            
            #line 189 "..\..\Views\Vacancy\BasicDetails.cshtml"
                                                                            
    
            
            #line default
            #line hidden
            
            #line 190 "..\..\Views\Vacancy\BasicDetails.cshtml"
Write(Html.HiddenFor(model => model.ProviderSiteEmployerLink.Employer.Ern));

            
            #line default
            #line hidden
            
            #line 190 "..\..\Views\Vacancy\BasicDetails.cshtml"
                                                                         ;
    
            
            #line default
            #line hidden
            
            #line 191 "..\..\Views\Vacancy\BasicDetails.cshtml"
Write(Html.HiddenFor(model => model.VacancyGuid));

            
            #line default
            #line hidden
            
            #line 191 "..\..\Views\Vacancy\BasicDetails.cshtml"
                                               


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"button\"");

WriteLiteral(">Save</button>\r\n    </div>\r\n");

            
            #line 196 "..\..\Views\Vacancy\BasicDetails.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script>\r\n        $(\"#");

            
            #line 201 "..\..\Views\Vacancy\BasicDetails.cshtml"
       Write(Html.NameFor(m => m.StandardId));

            
            #line default
            #line hidden
WriteLiteral("\").change(function () {\r\n            var apprenticeshipLevel = $(\"#");

            
            #line 202 "..\..\Views\Vacancy\BasicDetails.cshtml"
                                     Write(Html.NameFor(m => m.StandardId));

            
            #line default
            #line hidden
WriteLiteral(" option:selected\").attr(\"data-apprenticeship-level\");\r\n            if (apprentice" +
"shipLevel === \"");

            
            #line 203 "..\..\Views\Vacancy\BasicDetails.cshtml"
                                    Write(ApprenticeshipLevel.FoundationDegree.ToString());

            
            #line default
            #line hidden
WriteLiteral("\" || apprenticeshipLevel === \"");

            
            #line 203 "..\..\Views\Vacancy\BasicDetails.cshtml"
                                                                                                                  Write(ApprenticeshipLevel.Masters.ToString());

            
            #line default
            #line hidden
WriteLiteral("\") {\r\n                apprenticeshipLevel = \"");

            
            #line 204 "..\..\Views\Vacancy\BasicDetails.cshtml"
                                  Write(ApprenticeshipLevel.Degree.ToString());

            
            #line default
            #line hidden
WriteLiteral("\";\r\n            }\r\n            $(\"#apprenticeship-level-name\").text(apprenticeshi" +
"pLevel);\r\n        });\r\n    </script>\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
