#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.Apprenticeships.Web.Candidate.Views.ApprenticeshipSearch
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\ApprenticeshipSearch\_savedSearches.cshtml"
    using SFA.Apprenticeships.Domain.Entities.Vacancies.Apprenticeships;
    
    #line default
    #line hidden
    using SFA.Apprenticeships.Web.Candidate;
    using SFA.Apprenticeships.Web.Candidate.Constants;
    using SFA.Apprenticeships.Web.Candidate.Constants.ViewModels;
    using SFA.Apprenticeships.Web.Candidate.Helpers;
    using SFA.Apprenticeships.Web.Candidate.ViewModels;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.Candidate;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.Locations;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.Login;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.Register;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.VacancySearch;
    using SFA.Apprenticeships.Web.Common.Constants;
    using SFA.Apprenticeships.Web.Common.Framework;
    using SFA.Apprenticeships.Web.Common.Models.Common;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ApprenticeshipSearch/_savedSearches.cshtml")]
    public partial class savedSearches : System.Web.Mvc.WebViewPage<ApprenticeshipSearchViewModel>
    {
        public savedSearches()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\ApprenticeshipSearch\_savedSearches.cshtml"
  
    var divClass = Model.SearchMode == ApprenticeshipSearchMode.SavedSearches ? "active" : "";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" id=\"saved-searches\"");

WriteAttribute("class", Tuple.Create(" class=\"", 241), Tuple.Create("\"", 278)
, Tuple.Create(Tuple.Create("", 249), Tuple.Create("tabbed-element", 249), true)
, Tuple.Create(Tuple.Create(" ", 263), Tuple.Create("tab3", 264), true)
            
            #line 9 "..\..\Views\ApprenticeshipSearch\_savedSearches.cshtml"
, Tuple.Create(Tuple.Create(" ", 268), Tuple.Create<System.Object, System.Int32>(divClass
            
            #line default
            #line hidden
, 269), false)
);

WriteLiteral(">\r\n");

            
            #line 10 "..\..\Views\ApprenticeshipSearch\_savedSearches.cshtml"
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\ApprenticeshipSearch\_savedSearches.cshtml"
     if (Model.SavedSearches != null && Model.SavedSearches.Any())
    {


            
            #line default
            #line hidden
WriteLiteral("        <ul");

WriteLiteral(" id=\"saved-searches-list\"");

WriteLiteral(" class=\"list-text list-checkradio\"");

WriteLiteral(">\r\n");

            
            #line 14 "..\..\Views\ApprenticeshipSearch\_savedSearches.cshtml"
            
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\ApprenticeshipSearch\_savedSearches.cshtml"
             foreach (var savedSearch in Model.SavedSearches)
            {

            
            #line default
            #line hidden
WriteLiteral("                <li>\r\n                    <input");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" name=\"SavedSearchId\"");

WriteAttribute("id", Tuple.Create(" id=\"", 592), Tuple.Create("\"", 625)
, Tuple.Create(Tuple.Create("", 597), Tuple.Create("saved-search-", 597), true)
            
            #line 17 "..\..\Views\ApprenticeshipSearch\_savedSearches.cshtml"
, Tuple.Create(Tuple.Create("", 610), Tuple.Create<System.Object, System.Int32>(savedSearch.Id
            
            #line default
            #line hidden
, 610), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 626), Tuple.Create("\"", 649)
            
            #line 17 "..\..\Views\ApprenticeshipSearch\_savedSearches.cshtml"
                       , Tuple.Create(Tuple.Create("", 634), Tuple.Create<System.Object, System.Int32>(savedSearch.Id
            
            #line default
            #line hidden
, 634), false)
);

WriteLiteral(">\r\n                    <label");

WriteAttribute("id", Tuple.Create(" id=\"", 679), Tuple.Create("\"", 718)
, Tuple.Create(Tuple.Create("", 684), Tuple.Create("saved-search-label-", 684), true)
            
            #line 18 "..\..\Views\ApprenticeshipSearch\_savedSearches.cshtml"
, Tuple.Create(Tuple.Create("", 703), Tuple.Create<System.Object, System.Int32>(savedSearch.Id
            
            #line default
            #line hidden
, 703), false)
);

WriteAttribute("for", Tuple.Create(" for=\"", 719), Tuple.Create("\"", 753)
, Tuple.Create(Tuple.Create("", 725), Tuple.Create("saved-search-", 725), true)
            
            #line 18 "..\..\Views\ApprenticeshipSearch\_savedSearches.cshtml"
      , Tuple.Create(Tuple.Create("", 738), Tuple.Create<System.Object, System.Int32>(savedSearch.Id
            
            #line default
            #line hidden
, 738), false)
);

WriteLiteral(">");

            
            #line 18 "..\..\Views\ApprenticeshipSearch\_savedSearches.cshtml"
                                                                                                 Write(savedSearch.Name);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                    \r\n");

            
            #line 20 "..\..\Views\ApprenticeshipSearch\_savedSearches.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\ApprenticeshipSearch\_savedSearches.cshtml"
                     if (savedSearch.ApprenticeshipLevel != "All")
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <p");

WriteLiteral(" class=\"font-xsmall no-btm-margin\"");

WriteLiteral(">\r\n                            <b>Apprenticeship level:</b> <span");

WriteAttribute("id", Tuple.Create(" id=\"", 1020), Tuple.Create("\"", 1074)
, Tuple.Create(Tuple.Create("", 1025), Tuple.Create("saved-search-apprenticeship-level-", 1025), true)
            
            #line 23 "..\..\Views\ApprenticeshipSearch\_savedSearches.cshtml"
                     , Tuple.Create(Tuple.Create("", 1059), Tuple.Create<System.Object, System.Int32>(savedSearch.Id
            
            #line default
            #line hidden
, 1059), false)
);

WriteLiteral(">");

            
            #line 23 "..\..\Views\ApprenticeshipSearch\_savedSearches.cshtml"
                                                                                                                 Write(savedSearch.ApprenticeshipLevel);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                        </p>\r\n");

            
            #line 25 "..\..\Views\ApprenticeshipSearch\_savedSearches.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    \r\n");

            
            #line 27 "..\..\Views\ApprenticeshipSearch\_savedSearches.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\ApprenticeshipSearch\_savedSearches.cshtml"
                     if (!string.IsNullOrWhiteSpace(savedSearch.SubCategoriesFullNames))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <p");

WriteLiteral(" class=\"font-xsmall no-btm-margin\"");

WriteLiteral(">\r\n                            <b>Sub-categories:</b> <span");

WriteAttribute("id", Tuple.Create(" id=\"", 1424), Tuple.Create("\"", 1471)
, Tuple.Create(Tuple.Create("", 1429), Tuple.Create("saved-search-subcategories-", 1429), true)
            
            #line 30 "..\..\Views\ApprenticeshipSearch\_savedSearches.cshtml"
        , Tuple.Create(Tuple.Create("", 1456), Tuple.Create<System.Object, System.Int32>(savedSearch.Id
            
            #line default
            #line hidden
, 1456), false)
);

WriteLiteral(">");

            
            #line 30 "..\..\Views\ApprenticeshipSearch\_savedSearches.cshtml"
                                                                                                    Write(savedSearch.SubCategoriesFullNames);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                        </p>\r\n");

            
            #line 32 "..\..\Views\ApprenticeshipSearch\_savedSearches.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </li>\r\n");

            
            #line 34 "..\..\Views\ApprenticeshipSearch\_savedSearches.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </ul>\r\n");

            
            #line 36 "..\..\Views\ApprenticeshipSearch\_savedSearches.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <p>\r\n        You can edit your saved searches in the\r\n");

WriteLiteral("        ");

            
            #line 39 "..\..\Views\ApprenticeshipSearch\_savedSearches.cshtml"
   Write(Html.RouteLink("alert settings", CandidateRouteNames.SavedSearchesSettings, null, new { id = "saved-searches-settings-link" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        section.\r\n    </p>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
