#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.Apprenticeships.Web.Candidate.Views.ApprenticeshipSearch
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
    using SFA.Apprenticeships.Domain.Entities.Vacancies;
    
    #line default
    #line hidden
    using SFA.Apprenticeships.Infrastructure.Presentation;
    using SFA.Apprenticeships.Web.Candidate;
    using SFA.Apprenticeships.Web.Candidate.Constants;
    using SFA.Apprenticeships.Web.Candidate.Constants.ViewModels;
    using SFA.Apprenticeships.Web.Candidate.Helpers;
    using SFA.Apprenticeships.Web.Candidate.ViewModels;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.Candidate;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.Login;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.Register;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.VacancySearch;
    using SFA.Apprenticeships.Web.Common.Constants;
    using SFA.Apprenticeships.Web.Common.Framework;
    using SFA.Apprenticeships.Web.Common.Models.Common;
    using SFA.Apprenticeships.Web.Common.ViewModels.Locations;
    using SFA.Apprenticeships.Web.Common.Views.Shared.DisplayTemplates;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ApprenticeshipSearch/_searchResults.cshtml")]
    public partial class searchResults : System.Web.Mvc.WebViewPage<ApprenticeshipSearchResponseViewModel>
    {
        public searchResults()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
 if (Model.TotalLocalHits == 0 && Model.TotalNationalHits == 0)
{

            
            #line default
            #line hidden
WriteLiteral("    <p");

WriteLiteral(" id=\"search-no-results-title\"");

WriteLiteral(">There are currently no apprenticeships that match your search.</p>\r\n");

WriteLiteral("    <p>Try editing your search:</p>\r\n");

WriteLiteral("    <ul");

WriteLiteral(" id=\"search-no-results\"");

WriteLiteral(" class=\"list list-bullet\"");

WriteLiteral(">\r\n");

            
            #line 10 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
        
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
         if (Model.VacancySearch.SearchMode == ApprenticeshipSearchMode.Keyword)
        {
            if (VacancyHelper.IsVacancyReference(Model.VacancySearch.Keywords))
            {

            
            #line default
            #line hidden
WriteLiteral("                <li");

WriteLiteral(" id=\"search-no-results-reference-number\"");

WriteLiteral(">try a different reference number</li>\r\n");

            
            #line 15 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <li");

WriteLiteral(" id=\"search-no-results-keywords\"");

WriteLiteral(">using different keywords</li>\r\n");

            
            #line 19 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
            }

        }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 22 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
         if (Model.VacancySearch.SearchMode == ApprenticeshipSearchMode.Category)
        {
            if (Model.VacancySearch.SubCategories == null || Model.VacancySearch.SubCategories.Length == 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <li");

WriteLiteral(" id=\"search-no-results-category\"");

WriteLiteral(">try a different category</li>\r\n");

            
            #line 27 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <li");

WriteLiteral(" id=\"search-no-results-sub-category\"");

WriteLiteral(">select a different sub-category or sub-categories</li>\r\n");

            
            #line 31 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
            }
        }

            
            #line default
            #line hidden
WriteLiteral("        <li>expanding your search location</li>\r\n");

            
            #line 34 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
        
            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
         if (Model.VacancySearch.ApprenticeshipLevel != "All")
        {

            
            #line default
            #line hidden
WriteLiteral("            <li");

WriteLiteral(" id=\"search-no-results-apprenticeship-levels\"");

WriteLiteral(">using a different level, or change to all levels</li>\r\n");

            
            #line 37 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </ul>\r\n");

WriteLiteral("    <div>\r\n");

            
            #line 40 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
        
            
            #line default
            #line hidden
            
            #line 40 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
         if (Model.VacancySearch.SearchMode == ApprenticeshipSearchMode.Keyword)
        {

            
            #line default
            #line hidden
WriteLiteral("            <p");

WriteLiteral(" id=\"search-no-results-trybrowse\"");

WriteLiteral(">Alternatively, try <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1740), Tuple.Create("\"", 1858)
            
            #line 42 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
, Tuple.Create(Tuple.Create("", 1747), Tuple.Create<System.Object, System.Int32>(Url.RouteUrl(CandidateRouteNames.ApprenticeshipSearch, new { searchMode = ApprenticeshipSearchMode.Category })
            
            #line default
            #line hidden
, 1747), false)
);

WriteLiteral(">browsing by category</a> to find an apprenticeship.</p>\r\n");

            
            #line 43 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");

            
            #line 45 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <fieldset>\r\n        <legend");

WriteLiteral(" class=\"visuallyhidden\"");

WriteLiteral(">Search items</legend>\r\n        <div");

WriteLiteral(" class=\"grid-row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"column-one-third\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"width-all-1-3 hide-js inl-block\"");

WriteLiteral("></div>\r\n                <div");

WriteLiteral(" class=\"hide-nojs form-group\"");

WriteLiteral(">\r\n                    <details");

WriteLiteral(" class=\"sfa-no-bottom-margin sfa-small-top-padding\"");

WriteLiteral(">\r\n                        <summary><span");

WriteLiteral(" class=\"summary\"");

WriteLiteral(">More/less detail</span></summary>\r\n                        <div");

WriteLiteral(" class=\"panel panel-border-narrow\"");

WriteLiteral(" id=\"chooseDetails\"");

WriteLiteral(">\r\n                            <ul");

WriteLiteral(" class=\"list list-checkradio font-xsmall\"");

WriteLiteral(">\r\n");

            
            #line 58 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 58 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                 if (Model.VacancySearch.SearchMode == ApprenticeshipSearchMode.Category)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li>\r\n                                       " +
" <input ");

            
            #line 61 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                                 if (Model.VacancySearch.DisplaySubCategory) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral(" checked=\"checked\" ");

WriteLiteral("     ");

            
            #line 61 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                                                                                                                    }
            
            #line default
            #line hidden
WriteLiteral(" type=\"checkbox\" id=\"DisplaySubCategory\">\r\n                                      " +
"  <label");

WriteLiteral(" for=\"DisplaySubCategory\"");

WriteLiteral(">Sub-category</label>\r\n                                    </li>\r\n");

            
            #line 64 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("                                <li>\r\n                                    <input " +
"");

            
            #line 66 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                             if (Model.VacancySearch.DisplayDescription) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral(" checked=\"checked\" ");

WriteLiteral("     ");

            
            #line 66 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                                                                                                                }
            
            #line default
            #line hidden
WriteLiteral(" type=\"checkbox\" id=\"DisplayDescription\">\r\n                                    <l" +
"abel");

WriteLiteral(" for=\"DisplayDescription\"");

WriteLiteral(">Description</label>\r\n                                </li>\r\n");

            
            #line 69 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 69 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                 if (Model.VacancySearch.LocationType == VacancyLocationType.NonNational)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li>\r\n                                       " +
" <input ");

            
            #line 72 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                                 if (Model.VacancySearch.DisplayDistance) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral(" checked=\"checked\" ");

WriteLiteral("     ");

            
            #line 72 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                                                                                                                 }
            
            #line default
            #line hidden
WriteLiteral(" type=\"checkbox\" id=\"DisplayDistance\">\r\n                                        <" +
"label");

WriteLiteral(" for=\"DisplayDistance\"");

WriteLiteral(">Distance</label>\r\n                                    </li>\r\n");

            
            #line 75 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("                                <li>\r\n                                    <input " +
"");

            
            #line 77 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                             if (Model.VacancySearch.DisplayClosingDate) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral(" checked=\"checked\" ");

WriteLiteral("     ");

            
            #line 77 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                                                                                                                }
            
            #line default
            #line hidden
WriteLiteral(" type=\"checkbox\" id=\"DisplayClosingDate\">\r\n                                    <l" +
"abel");

WriteLiteral(" for=\"DisplayClosingDate\"");

WriteLiteral(">Closing date</label>\r\n                                </li>\r\n                   " +
"             <li>\r\n                                    <input ");

            
            #line 81 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                             if (Model.VacancySearch.DisplayStartDate) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral(" checked=\"checked\" ");

WriteLiteral("     ");

            
            #line 81 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                                                                                                              }
            
            #line default
            #line hidden
WriteLiteral(" type=\"checkbox\" id=\"DisplayStartDate\">\r\n                                    <lab" +
"el");

WriteLiteral(" for=\"DisplayStartDate\"");

WriteLiteral(">Possible start date</label>\r\n                                </li>\r\n            " +
"                    <li>\r\n                                    <input ");

            
            #line 85 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                             if (Model.VacancySearch.DisplayApprenticeshipLevel) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral(" checked=\"checked\" ");

WriteLiteral("     ");

            
            #line 85 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                                                                                                                        }
            
            #line default
            #line hidden
WriteLiteral(" type=\"checkbox\" id=\"DisplayApprenticeshipLevel\">\r\n                              " +
"      <label");

WriteLiteral(" for=\"DisplayApprenticeshipLevel\"");

WriteLiteral(">Apprenticeship level</label>\r\n                                </li>\r\n           " +
"                     <li>\r\n                                    <input ");

            
            #line 89 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                             if (Model.VacancySearch.DisplayWage) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral(" checked=\"checked\" ");

WriteLiteral("     ");

            
            #line 89 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                                                                                                         }
            
            #line default
            #line hidden
WriteLiteral(" type=\"checkbox\" id=\"DisplayWage\">\r\n                                    <label");

WriteLiteral(" for=\"DisplayWage\"");

WriteLiteral(">Wage</label>\r\n                                </li>\r\n                           " +
" </ul>\r\n                        </div>\r\n                    </details>\r\n        " +
"        </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"column-two-thirds sfa-align-right-tablet\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"sort-results\"");

WriteLiteral(" class=\"heading-medium sfa-medium-right-margin\"");

WriteLiteral(">Sort results</label>\r\n");

WriteLiteral("                    ");

            
            #line 100 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
               Write(Html.DropDownList("sortType", Model.SortTypes, new { @id = "sort-results", @class = "form-control form-control-auto" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <noscript>\r\n                        <button");

WriteLiteral(" style=\"float: right; margin-left: 5px;\"");

WriteLiteral(" class=\"button show-nojs\"");

WriteLiteral(" name=\"SearchAction\"");

WriteLiteral(" value=\"Sort\"");

WriteLiteral(">Sort</button>\r\n                    </noscript>\r\n                    <input");

WriteLiteral(" id=\"SearchAction\"");

WriteLiteral(" name=\"SearchAction\"");

WriteLiteral(" value=\"Search\"");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" />\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </fieldset>\r" +
"\n");

            
            #line 109 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <ul");

WriteLiteral(" class=\"search-results\"");

WriteLiteral(">\r\n");

            
            #line 111 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
        
            
            #line default
            #line hidden
            
            #line 111 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
         if (Model.Vacancies != null)
        {
            var itemPosition = 1 + (Model.PageSize * Model.PrevPage);
            foreach (var vacancy in Model.Vacancies)
            {
                var webTrendItemPositionTracker = "Webtrends.multiTrack({ element: this, argsa: ['DCS.dcsuri', '/apprenticeships/results/itemposition/" + vacancy.Id + "', 'WT.dl', '99', 'WT.ti', 'Apprenticeships Search – Item Position Clicked', 'DCSext.ipos', '" + itemPosition + "'] })";

            
            #line default
            #line hidden
WriteLiteral("                <li");

WriteLiteral(" class=\"search-result sfa-section-bordered\"");

WriteLiteral(">\r\n                    <h2");

WriteLiteral(" class=\"heading-medium sfa-no-margins\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 119 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                    Write(vacancy.VacancyLocationType == VacancyLocationType.NonNational ?
                                Html.ActionLink(@vacancy.Title, "DetailsWithDistance", new { id = vacancy.Id, distance = vacancy.DistanceAsString }, new { @class = "vacancy-link", data_vacancy_id = vacancy.Id, onclick = webTrendItemPositionTracker, data_lat = vacancy.Location.Latitude, data_lon = vacancy.Location.Longitude, data_is_employer_anonymous = vacancy.IsEmployerAnonymous }) :
                                Html.ActionLink(@vacancy.Title, "DetailsWithDistance", new { id = vacancy.Id, distance = vacancy.DistanceAsString }, new { @class = "vacancy-link", data_vacancy_id = vacancy.Id, onclick = webTrendItemPositionTracker }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </h2>\r\n                    <ul");

WriteLiteral(" class=\"list\"");

WriteLiteral(">\r\n");

            
            #line 124 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 124 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                         if (Model.VacancySearch.SearchMode == ApprenticeshipSearchMode.Category)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li>");

            
            #line 126 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                           Write(FullNameFormatter.Format(vacancy.SubCategory));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");

            
            #line 127 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <li");

WriteLiteral(" class=\"secondary-text\"");

WriteLiteral(">");

            
            #line 128 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                              Write(vacancy.EmployerName);

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                        <li");

WriteLiteral(" class=\"font-xsmall secondary-text\"");

WriteLiteral(">\r\n");

            
            #line 130 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 130 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                             if (vacancy.VacancyLocationType == VacancyLocationType.NonNational)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <span");

WriteAttribute("id", Tuple.Create(" id=\"", 8145), Tuple.Create("\"", 8173)
, Tuple.Create(Tuple.Create("", 8150), Tuple.Create("posted-date-", 8150), true)
            
            #line 132 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
, Tuple.Create(Tuple.Create("", 8162), Tuple.Create<System.Object, System.Int32>(vacancy.Id
            
            #line default
            #line hidden
, 8162), false)
);

WriteLiteral(">(Added ");

            
            #line 132 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                                                     Write(vacancy.PostedDate.ToFriendlyDaysAgo());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

WriteLiteral("                                <span");

WriteAttribute("id", Tuple.Create(" id=\"", 8267), Tuple.Create("\"", 8303)
, Tuple.Create(Tuple.Create("", 8272), Tuple.Create("number-of-positions-", 8272), true)
            
            #line 133 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
, Tuple.Create(Tuple.Create("", 8292), Tuple.Create<System.Object, System.Int32>(vacancy.Id
            
            #line default
            #line hidden
, 8292), false)
);

WriteLiteral(">\r\n");

            
            #line 134 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 134 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                     if (vacancy.NumberOfPositions == 1)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        ");

WriteLiteral("- 1 position available)");

WriteLiteral("\r\n");

            
            #line 137 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                    }
                                    else
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        ");

WriteLiteral("- ");

            
            #line 140 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                           Write(vacancy.NumberOfPositions);

            
            #line default
            #line hidden
WriteLiteral(" positions available)");

WriteLiteral("\r\n");

            
            #line 141 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </span>\r\n");

            
            #line 143 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                            }
                            else
                            {

            
            #line default
            #line hidden
WriteLiteral("                                ");

WriteLiteral("(Added ");

            
            #line 146 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                        Write(vacancy.PostedDate.ToFriendlyDaysAgo());

            
            #line default
            #line hidden
WriteLiteral(")");

WriteLiteral("\r\n");

            
            #line 147 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </li>\r\n                    </ul>\r\n                    <" +
"p");

WriteLiteral(" data-show=\"DisplayDescription\"");

WriteAttribute("class", Tuple.Create(" class=\"", 9136), Tuple.Create("\"", 9210)
            
            #line 151 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
, Tuple.Create(Tuple.Create("", 9144), Tuple.Create<System.Object, System.Int32>(!Model.VacancySearch.DisplayDescription ? "toggle-content" : ""
            
            #line default
            #line hidden
, 9144), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 152 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                   Write(vacancy.Description);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </p>\r\n                    <div");

WriteLiteral(" class=\"grid-row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"column-two-thirds\"");

WriteLiteral(">\r\n                            <ul");

WriteAttribute("class", Tuple.Create(" class=\"", 9418), Tuple.Create("\"", 9530)
, Tuple.Create(Tuple.Create("", 9426), Tuple.Create("list", 9426), true)
, Tuple.Create(Tuple.Create(" ", 9430), Tuple.Create("sfa-no-margins", 9431), true)
, Tuple.Create(Tuple.Create(" ", 9445), Tuple.Create("vacancy-details-list", 9446), true)
            
            #line 156 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
, Tuple.Create(Tuple.Create(" ", 9466), Tuple.Create<System.Object, System.Int32>(!Model.VacancySearch.DisplayDistance ? "toggle-content" : ""
            
            #line default
            #line hidden
, 9467), false)
);

WriteLiteral(">\r\n");

            
            #line 157 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 157 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                 if (vacancy.VacancyLocationType == VacancyLocationType.NonNational)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li");

WriteLiteral(" data-show=\"DisplayDistance\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"bold-small\"");

WriteLiteral(">Distance:</span> <span");

WriteLiteral(" id=\"distance-value\"");

WriteLiteral(">");

            
            #line 160 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                                                                                       Write(vacancy.DistanceAsString);

            
            #line default
            #line hidden
WriteLiteral("</span> miles\r\n\r\n                                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"summary-style hide-nojs journey-trigger\"");

WriteLiteral(">Journey time</a>\r\n                                        <div");

WriteLiteral(" class=\"detail-content toggle-content hide-nojs\"");

WriteLiteral(">\r\n                                            <select");

WriteLiteral(" class=\"form-control valid select-mode\"");

WriteLiteral(" name=\"\"");

WriteLiteral(" aria-invalid=\"false\"");

WriteLiteral(">\r\n                                                <option");

WriteLiteral(" value=\"DRIVING\"");

WriteLiteral(" aria-live=\"polite\"");

WriteLiteral(">Driving</option>\r\n                                                <option");

WriteLiteral(" value=\"TRANSIT\"");

WriteLiteral(" aria-live=\"polite\"");

WriteLiteral(">Bus/Train</option>\r\n                                                <option");

WriteLiteral(" value=\"WALKING\"");

WriteLiteral(" aria-live=\"polite\"");

WriteLiteral(">Walking</option>\r\n                                                <option");

WriteLiteral(" value=\"BICYCLING\"");

WriteLiteral(" aria-live=\"polite\"");

WriteLiteral(">Cycling</option>\r\n                                            </select>\r\n\r\n     " +
"                                       <span");

WriteLiteral(" class=\"journey-time\"");

WriteLiteral(" aria-live=\"polite\"");

WriteLiteral("></span>\r\n                                        </div>\r\n                       " +
"             </li>\r\n");

            
            #line 174 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                                <li");

WriteLiteral(" data-show=\"DisplayClosingDate\"");

WriteLiteral(">\r\n                                    <span");

WriteAttribute("class", Tuple.Create(" class=\"", 11058), Tuple.Create("\"", 11143)
, Tuple.Create(Tuple.Create("", 11066), Tuple.Create("bold-small", 11066), true)
            
            #line 176 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
, Tuple.Create(Tuple.Create(" ", 11076), Tuple.Create<System.Object, System.Int32>(!Model.VacancySearch.DisplayClosingDate ? "toggle-content" : ""
            
            #line default
            #line hidden
, 11077), false)
);

WriteLiteral(">Closing date:</span> <span");

WriteLiteral(" id=\"closing-date-value\"");

WriteLiteral(" data-date=\"");

            
            #line 176 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                                                                                                                                                                         Write(vacancy.ClosingDate.ToString("u"));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">");

            
            #line 176 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                                                                                                                                                                                                             Write(vacancy.ClosingDate.ToFriendlyClosingWeek());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n</li>\r\n                                <li");

WriteLiteral(" data-show=\"DisplayStartDate\"");

WriteLiteral(">\r\n                                    <span");

WriteAttribute("class", Tuple.Create(" class=\"", 11411), Tuple.Create("\"", 11494)
, Tuple.Create(Tuple.Create("", 11419), Tuple.Create("bold-small", 11419), true)
            
            #line 179 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
, Tuple.Create(Tuple.Create(" ", 11429), Tuple.Create<System.Object, System.Int32>(!Model.VacancySearch.DisplayStartDate ? "toggle-content" : ""
            
            #line default
            #line hidden
, 11430), false)
);

WriteLiteral(">Possible start date:</span> <span");

WriteLiteral(" id=\"start-date-value\"");

WriteLiteral(">");

            
            #line 179 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                                                                                                                                                                 Write(Html.DisplayFor(m => vacancy.StartDate, "Date"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                </li>\r\n                                <" +
"li");

WriteLiteral(" data-show=\"DisplayApprenticeshipLevel\"");

WriteAttribute("class", Tuple.Create(" class=\"", 11722), Tuple.Create("\"", 11804)
            
            #line 181 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
  , Tuple.Create(Tuple.Create("", 11730), Tuple.Create<System.Object, System.Int32>(!Model.VacancySearch.DisplayApprenticeshipLevel ? "toggle-content" : ""
            
            #line default
            #line hidden
, 11730), false)
);

WriteLiteral(">\r\n                                    <span");

WriteLiteral(" class=\"bold-small\"");

WriteLiteral(">Apprenticeship level:</span> ");

            
            #line 182 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                                                                     Write(vacancy.ApprenticeshipLevel);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </li>\r\n                                <li");

WriteLiteral(" data-show=\"DisplayWage\"");

WriteAttribute("class", Tuple.Create(" class=\"", 12026), Tuple.Create("\"", 12093)
            
            #line 184 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
, Tuple.Create(Tuple.Create("", 12034), Tuple.Create<System.Object, System.Int32>(!Model.VacancySearch.DisplayWage ? "toggle-content" : ""
            
            #line default
            #line hidden
, 12034), false)
);

WriteLiteral(">\r\n                                    <span");

WriteLiteral(" class=\"bold-small\"");

WriteLiteral(">Wage:</span> ");

            
            #line 185 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                                                     Write(WagePresenter.GetDisplayAmountWithFrequencyPostfix(vacancy.Wage.Type, vacancy.Wage.Amount, vacancy.Wage.AmountLowerBound, vacancy.Wage.AmountUpperBound, vacancy.Wage.Text, vacancy.Wage.Unit, vacancy.Wage.HoursPerWeek, vacancy.StartDate));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </li>\r\n\r\n");

            
            #line 188 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 188 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                 if (vacancy.IsPositiveAboutDisability)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li>\r\n                                       " +
" <a");

WriteAttribute("id", Tuple.Create(" id=\"", 12643), Tuple.Create("\"", 12683)
, Tuple.Create(Tuple.Create("", 12648), Tuple.Create("positive-about-disabled-", 12648), true)
            
            #line 191 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
, Tuple.Create(Tuple.Create("", 12672), Tuple.Create<System.Object, System.Int32>(vacancy.Id
            
            #line default
            #line hidden
, 12672), false)
);

WriteLiteral(" href=\"https://www.gov.uk/looking-for-work-if-disabled\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n                                            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 12806), Tuple.Create("\"", 12852)
            
            #line 192 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
, Tuple.Create(Tuple.Create("", 12812), Tuple.Create<System.Object, System.Int32>(Url.CdnImage("logo-ticks-small-2x.png")
            
            #line default
            #line hidden
, 12812), false)
);

WriteLiteral(" height=\"30\"");

WriteLiteral(" width=\"38\"");

WriteLiteral(" alt=\"Two ticks logo - Positive about disabled people\"");

WriteLiteral(">\r\n                                        </a>\r\n                                " +
"    </li>\r\n");

            
            #line 195 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                                ");

            
            #line 196 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                 if (vacancy.VacancyLocationType == VacancyLocationType.NonNational)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li");

WriteLiteral(" class=\"sfa-hide-tablet hide-nojs\"");

WriteLiteral(">\r\n                                        <a");

WriteLiteral(" href=\"#1\"");

WriteLiteral(" class=\"mob-map-trigger summary-style map-closed\"");

WriteLiteral(">Show/hide map</a>\r\n                                    </li>\r\n");

            
            #line 201 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 203 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 203 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                 if (vacancy.VacancyLocationType == VacancyLocationType.National)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li");

WriteLiteral(" id=\"multiple-positions-nationwide\"");

WriteLiteral(">\r\n                                        This apprenticeship has multiple posit" +
"ions across England.\r\n                                    </li>\r\n");

            
            #line 208 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </ul>\r\n                        </div>\r\n");

            
            #line 211 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 211 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                         if (vacancy.VacancyLocationType == VacancyLocationType.NonNational)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"column-one-third map-container hide-nojs sfa-small-bottom-margin toggle-c" +
"ontent--mob\"");

WriteLiteral(">\r\n                                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 14210), Tuple.Create("\"", 14320)
, Tuple.Create(Tuple.Create("", 14217), Tuple.Create("https://www.google.com/maps/dir/LocationLatLon/\'", 14217), true)
            
            #line 214 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
        , Tuple.Create(Tuple.Create("", 14265), Tuple.Create<System.Object, System.Int32>(vacancy.Location.Latitude
            
            #line default
            #line hidden
, 14265), false)
, Tuple.Create(Tuple.Create("", 14291), Tuple.Create(",", 14291), true)
            
            #line 214 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                   , Tuple.Create(Tuple.Create("", 14292), Tuple.Create<System.Object, System.Int32>(vacancy.Location.Longitude
            
            #line default
            #line hidden
, 14292), false)
, Tuple.Create(Tuple.Create("", 14319), Tuple.Create("\'", 14319), true)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" rel=\"external\"");

WriteLiteral(" class=\"map-links fake-link font-xxsmall view-googlemaps\"");

WriteLiteral(">Open map</a>\r\n                                <div");

WriteLiteral(" class=\"map-placeholder\"");

WriteLiteral("></div>\r\n                                <img");

WriteLiteral(" class=\"static-map\"");

WriteAttribute("src", Tuple.Create(" src=\"", 14548), Tuple.Create("\"", 14582)
            
            #line 216 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
, Tuple.Create(Tuple.Create("", 14554), Tuple.Create<System.Object, System.Int32>(vacancy.GoogleStaticMapsUrl
            
            #line default
            #line hidden
, 14554), false)
);

WriteLiteral("/>\r\n                            </div>\r\n");

            
            #line 218 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n\r\n");

            
            #line 221 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 221 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                     if (ViewBag.IsCandidateActivated != null && ViewBag.IsCandidateActivated)
                        {
                            var applicationStatus = vacancy.CandidateApplicationStatus.HasValue
                                ? vacancy.CandidateApplicationStatus.ToString()
                                : "Unsaved";


            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"save-vacancy\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteAttribute("id", Tuple.Create(" id=\"", 15120), Tuple.Create("\"", 15154)
, Tuple.Create(Tuple.Create("", 15125), Tuple.Create("save-vacancy-link-", 15125), true)
            
            #line 228 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
, Tuple.Create(Tuple.Create("", 15143), Tuple.Create<System.Object, System.Int32>(vacancy.Id
            
            #line default
            #line hidden
, 15143), false)
);

WriteLiteral(" class=\"hidden fake-link link-unimp save-vacancy-link\"");

WriteLiteral(" data-vacancy-id=\"");

            
            #line 228 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                                                                                                                             Write(vacancy.Id);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-application-status=\"");

            
            #line 228 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                                                                                                                                                                                   Write(applicationStatus);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa\"");

WriteLiteral("></i></a>\r\n");

WriteLiteral("                            ");

            
            #line 229 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                       Write(Html.ActionLink("Resume", "Resume", "ApprenticeshipApplication", new { id = vacancy.Id }, new { @class = "hidden resume-link", @id = "resume-link-" + @vacancy.Id }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <p");

WriteAttribute("id", Tuple.Create(" id=\"", 15534), Tuple.Create("\"", 15564)
, Tuple.Create(Tuple.Create("", 15539), Tuple.Create("applied-label-", 15539), true)
            
            #line 230 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
, Tuple.Create(Tuple.Create("", 15553), Tuple.Create<System.Object, System.Int32>(vacancy.Id
            
            #line default
            #line hidden
, 15553), false)
);

WriteLiteral(" class=\"hidden applied-label\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral("></i>Applied\r\n                            </p>\r\n                        </div>\r\n");

            
            #line 234 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </li>\r\n");

            
            #line 236 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                itemPosition++;
            }
        }

            
            #line default
            #line hidden
WriteLiteral("    </ul>\r\n");

            
            #line 240 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"

    Html.RenderPartial("_pagination", Model);

    if (Model.TotalLocalHits > 5 || Model.TotalNationalHits > 5)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"form-group sfa-medium-top-margin\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" for=\"results-per-page\"");

WriteLiteral(" class=\"heading-small inline\"");

WriteLiteral(">Display results</label>\r\n");

WriteLiteral("            ");

            
            #line 247 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
       Write(Html.DropDownList("resultsPerPage", Model.ResultsPerPageSelectList, new { @id = "results-per-page", @class = "form-control form-control-auto" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <noscript>\r\n                <button");

WriteLiteral(" class=\"button show-nojs\"");

WriteLiteral(" name=\"ChangeResultsPerPageAction\"");

WriteLiteral(" value=\"ResultsPerPage\"");

WriteLiteral(">View</button>\r\n            </noscript>\r\n        </div>\r\n");

            
            #line 252 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
        }
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 256 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
 if (Request.IsAjaxRequest())
{

            
            #line default
            #line hidden
WriteLiteral("    <script>\r\n        initSavedVacancies({\r\n            saveUrl: \'");

            
            #line 260 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                 Write(Url.RouteUrl(CandidateRouteNames.ApprenticeshipSaveVacancy));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n            deleteUrl: \'");

            
            #line 261 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
                   Write(Url.RouteUrl(CandidateRouteNames.ApprenticeshipDeleteSavedVacancy));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n            title: true\r\n        });\r\n    </script>\r\n");

            
            #line 265 "..\..\Views\ApprenticeshipSearch\_searchResults.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
