// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SFA.DAS.RAA.Api.Client.V1.Models
{
    using System.Linq;

    public partial class Wage
    {
        /// <summary>
        /// Initializes a new instance of the Wage class.
        /// </summary>
        public Wage() { }

        /// <summary>
        /// Initializes a new instance of the Wage class.
        /// </summary>
        public Wage(int? type = default(int?), string reasonForType = default(string), double? amount = default(double?), double? amountLowerBound = default(double?), double? amountUpperBound = default(double?), string text = default(string), int? unit = default(int?), double? hoursPerWeek = default(double?))
        {
            Type = type;
            ReasonForType = reasonForType;
            Amount = amount;
            AmountLowerBound = amountLowerBound;
            AmountUpperBound = amountUpperBound;
            Text = text;
            Unit = unit;
            HoursPerWeek = hoursPerWeek;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Type")]
        public int? Type { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ReasonForType")]
        public string ReasonForType { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Amount")]
        public double? Amount { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "AmountLowerBound")]
        public double? AmountLowerBound { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "AmountUpperBound")]
        public double? AmountUpperBound { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Text")]
        public string Text { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Unit")]
        public int? Unit { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "HoursPerWeek")]
        public double? HoursPerWeek { get; private set; }

    }
}
