CREATE TABLE [Vacancy].[Vacancy]
(
	[VacancyId] INT NOT NULL PRIMARY KEY, 
    [VacancyReferenceNumber] INT NOT NULL, 
    [Title] NVARCHAR(100) NOT NULL, 
    [ShortDescription] NVARCHAR(50) NULL, 
    [Description] NVARCHAR(MAX) NULL, 
    [AV_WorkingWeekText] NVARCHAR(50) NULL, 
    [VacancyStatusCode] CHAR(3) NOT NULL, 
    [WageValue] MONEY NULL, 
    [WageTypeCode] CHAR(3) NULL, 
    [AV_WageText] NVARCHAR(50) NULL, 
    [ApplicationClosingDate] DATETIME2 NULL, 
    [StartDate] DATETIME2 NULL, 
    [DurationValue] SMALLINT NULL, 
    [DurationTypeCode] CHAR(3) NULL, 
    [WorkingWeekText] NVARCHAR(MAX) NULL, 
    [HoursPerWeek] DECIMAL(10, 2) NULL, 
    [EmployerOrganisationSiteId] INT NULL, 
    [EmployerDescription] NVARCHAR(MAX) NULL, 
    [DirectApplicationUrl] NVARCHAR(MAX) NULL, 
    [DirectApplicationUrlQAComment] NVARCHAR(MAX) NULL, 
    [IsEmployerDirectApplication] BIT NULL, 
    [DirectApplicationInstructions] NVARCHAR(MAX) NULL, 
    [VacancyLocationTypeCode] CHAR NULL, 
    [ManagerOrganisationSiteId] INT NULL, 
    [DeliveryOrganisationSiteId] INT NULL, 
    [ContractOwnerOrganisationSiteId] INT NULL, 
    [OriginalContractOwnerOrganisationSiteId] INT NULL, 
    CONSTRAINT [FK_Vacancy_VacancyStatus] FOREIGN KEY ([VacancyStatusCode]) REFERENCES [Vacancy].[VacancyStatus]([VacancyStatusCode]), 
    CONSTRAINT [FK_Vacancy_WageType] FOREIGN KEY ([WageTypeCode]) REFERENCES [Vacancy].[WageType]([WageTypeCode]), 
    CONSTRAINT [FK_Vacancy_DurationType] FOREIGN KEY ([DurationTypeCode]) REFERENCES [Vacancy].[DurationType]([DurationTypeCode]), 
    CONSTRAINT [FK_Vacancy_EmployerOrganisationSiteId_OrganisationSite] FOREIGN KEY ([EmployerOrganisationSiteId]) REFERENCES [Organisation].[OrganisationSite]([OrganisationSiteId]),
    CONSTRAINT [FK_Vacancy_ManagerOrganisationSiteId_OrganisationSite] FOREIGN KEY ([ManagerOrganisationSiteId]) REFERENCES [Organisation].[OrganisationSite]([OrganisationSiteId]),
    CONSTRAINT [FK_Vacancy_DeliveryOrganisationSiteId_OrganisationSite] FOREIGN KEY ([DeliveryOrganisationSiteId]) REFERENCES [Organisation].[OrganisationSite]([OrganisationSiteId]),
    CONSTRAINT [FK_Vacancy_ContractOwnerOrganisationSiteId_OrganisationSite] FOREIGN KEY ([ContractOwnerOrganisationSiteId]) REFERENCES [Organisation].[OrganisationSite]([OrganisationSiteId]),
    CONSTRAINT [FK_Vacancy_OriginalContractOwnerOrganisationSiteId_OrganisationSite] FOREIGN KEY ([OriginalContractOwnerOrganisationSiteId]) REFERENCES [Organisation].[OrganisationSite]([OrganisationSiteId]) 
)
