namespace SFA.Apprenticeships.Application.Interfaces.Communications
{
    public enum CommunicationTokens
    {
        CandidateFirstName = 0,
        CandidateLastName = 1,
        Username = 2,
        ActivationCode = 3,
        ActivationCodeExpiryDays = 4,
        PasswordResetCode = 5,
        PasswordResetCodeExpiryDays = 6,
        AccountUnlockCode = 7,
        AccountUnlockCodeExpiryDays = 8,
        MobileVerificationCode = 9,
        ApplicationVacancyTitle = 10,
        ApplicationVacancyReference = 11,
        ApplicationVacancyEmployerName = 12,
        ApplicationId = 13,
        ProviderContact = 14,
        RecipientEmailAddress = 15,
        CandidateMobileNumber = 16,
        ExpiringDraft = 17,
        ExpiringDrafts = 18,
        UserFullName = 19,
        UserEnquiry = 20,
        UserEnquiryDetails = 21,
        UserEmailAddress = 22,
        ApplicationStatusAlert = 23,
        ApplicationStatusAlerts = 24,
        SavedSearchAlerts = 25,
        UserPendingUsername = 26,
        UserPendingUsernameCode = 27,
        CandidateSiteDomainName = 28,
        CandidateSubscriberId = 29,
        CandidateSubscriptionType = 30,
        LastLogin = 31,
        AccountExpiryDate = 32,
        ProviderUserEmailVerificationCode = 33,
        ProviderUserFullName = 34,
        ProviderUserUsername = 35
    }
}
