#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.Apprenticeships.Web.Candidate.Views.ApprenticeshipApplication.DisplayTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SFA.Apprenticeships.Infrastructure.Presentation;
    using SFA.Apprenticeships.Web.Candidate;
    using SFA.Apprenticeships.Web.Candidate.Constants;
    using SFA.Apprenticeships.Web.Candidate.Constants.ViewModels;
    using SFA.Apprenticeships.Web.Candidate.Helpers;
    using SFA.Apprenticeships.Web.Candidate.ViewModels;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.Candidate;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.Login;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.Register;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.VacancySearch;
    using SFA.Apprenticeships.Web.Common.Constants;
    using SFA.Apprenticeships.Web.Common.Framework;
    using SFA.Apprenticeships.Web.Common.Models.Common;
    using SFA.Apprenticeships.Web.Common.ViewModels.Locations;
    using SFA.Apprenticeships.Web.Common.Views.Shared.DisplayTemplates;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ApprenticeshipApplication/DisplayTemplates/ApprenticeshipCandidateViewMod" +
        "el.cshtml")]
    public partial class ApprenticeshipCandidateViewModel_ : System.Web.Mvc.WebViewPage<ApprenticeshipCandidateViewModel>
    {
        public ApprenticeshipCandidateViewModel_()
        {
        }
        public override void Execute()
        {
WriteLiteral("<section");

WriteLiteral(" class=\"grid-row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"column-two-thirds\"");

WriteLiteral(">\r\n        <h3");

WriteLiteral(" class=\"heading-large\"");

WriteLiteral(">Your details</h3>\r\n        <div");

WriteLiteral(" class=\"grid-row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"column-one-half\"");

WriteLiteral(">\r\n                <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral(">Full name</h3>\r\n");

WriteLiteral("                ");

            
            #line 9 "..\..\Views\ApprenticeshipApplication\DisplayTemplates\ApprenticeshipCandidateViewModel.cshtml"
           Write(Html.HiddenFor(m => m.FirstName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 10 "..\..\Views\ApprenticeshipApplication\DisplayTemplates\ApprenticeshipCandidateViewModel.cshtml"
           Write(Html.HiddenFor(m => m.LastName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <span");

WriteLiteral(" id=\"candidate-fullname\"");

WriteLiteral(">");

            
            #line 11 "..\..\Views\ApprenticeshipApplication\DisplayTemplates\ApprenticeshipCandidateViewModel.cshtml"
                                         Write(Html.DisplayFor(model => model.FullName));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n\r\n                <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral(">Date of birth</h3>\r\n");

WriteLiteral("                ");

            
            #line 14 "..\..\Views\ApprenticeshipApplication\DisplayTemplates\ApprenticeshipCandidateViewModel.cshtml"
           Write(Html.HiddenFor(m => m.DateOfBirth));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <span");

WriteLiteral(" id=\"candidate-dob\"");

WriteLiteral(">");

            
            #line 15 "..\..\Views\ApprenticeshipApplication\DisplayTemplates\ApprenticeshipCandidateViewModel.cshtml"
                                    Write(Html.DisplayFor(model => model.DateOfBirth, "Date"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral(">Address</h3>\r\n                <ul");

WriteLiteral(" class=\"list\"");

WriteLiteral(">\r\n                    <li");

WriteLiteral(" id=\"candidate-address-line1\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 19 "..\..\Views\ApprenticeshipApplication\DisplayTemplates\ApprenticeshipCandidateViewModel.cshtml"
                   Write(Html.HiddenFor(m => m.Address.AddressLine1));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 20 "..\..\Views\ApprenticeshipApplication\DisplayTemplates\ApprenticeshipCandidateViewModel.cshtml"
                   Write(Model.Address.AddressLine1);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n                    <li");

WriteLiteral(" id=\"candidate-address-line2\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 23 "..\..\Views\ApprenticeshipApplication\DisplayTemplates\ApprenticeshipCandidateViewModel.cshtml"
                   Write(Html.HiddenFor(m => m.Address.AddressLine2));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 24 "..\..\Views\ApprenticeshipApplication\DisplayTemplates\ApprenticeshipCandidateViewModel.cshtml"
                   Write(Model.Address.AddressLine2);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n                    <li");

WriteLiteral(" id=\"candidate-address-line3\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 27 "..\..\Views\ApprenticeshipApplication\DisplayTemplates\ApprenticeshipCandidateViewModel.cshtml"
                   Write(Html.HiddenFor(m => m.Address.AddressLine3));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 28 "..\..\Views\ApprenticeshipApplication\DisplayTemplates\ApprenticeshipCandidateViewModel.cshtml"
                   Write(Model.Address.AddressLine3);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n                    <li");

WriteLiteral(" id=\"candidate-address-line4\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 31 "..\..\Views\ApprenticeshipApplication\DisplayTemplates\ApprenticeshipCandidateViewModel.cshtml"
                   Write(Html.HiddenFor(m => m.Address.AddressLine4));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 32 "..\..\Views\ApprenticeshipApplication\DisplayTemplates\ApprenticeshipCandidateViewModel.cshtml"
                   Write(Model.Address.AddressLine4);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n                    <li");

WriteLiteral(" id=\"candidate-address-postcode\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 35 "..\..\Views\ApprenticeshipApplication\DisplayTemplates\ApprenticeshipCandidateViewModel.cshtml"
                   Write(Html.HiddenFor(m => m.Address.Postcode));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 36 "..\..\Views\ApprenticeshipApplication\DisplayTemplates\ApprenticeshipCandidateViewModel.cshtml"
                   Write(Model.Address.Postcode);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n                </ul>\r\n            </div>\r\n         " +
"   <div");

WriteLiteral(" class=\"column-one-half\"");

WriteLiteral(">\r\n                <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral(">Email address</h3>\r\n");

WriteLiteral("                ");

            
            #line 42 "..\..\Views\ApprenticeshipApplication\DisplayTemplates\ApprenticeshipCandidateViewModel.cshtml"
           Write(Html.HiddenFor(m => m.EmailAddress));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <span");

WriteLiteral(" id=\"candidate-email\"");

WriteLiteral(">");

            
            #line 43 "..\..\Views\ApprenticeshipApplication\DisplayTemplates\ApprenticeshipCandidateViewModel.cshtml"
                                      Write(Model.EmailAddress);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral(">Phone</h3>\r\n");

WriteLiteral("                ");

            
            #line 45 "..\..\Views\ApprenticeshipApplication\DisplayTemplates\ApprenticeshipCandidateViewModel.cshtml"
           Write(Html.HiddenFor(m => m.PhoneNumber));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <span");

WriteLiteral(" id=\"candidate-phone\"");

WriteLiteral(">");

            
            #line 46 "..\..\Views\ApprenticeshipApplication\DisplayTemplates\ApprenticeshipCandidateViewModel.cshtml"
                                      Write(Model.PhoneNumber);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </div>\r\n        </div>\r\n        <hr />\r\n    </div>\r\n</sectio" +
"n>");

        }
    }
}
#pragma warning restore 1591
