#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.Apprenticeships.Web.Candidate.Views.TraineeshipSearch
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\TraineeshipSearch\Details.cshtml"
    using SFA.Apprenticeships.Domain.Entities.Vacancies.Apprenticeships;
    
    #line default
    #line hidden
    using SFA.Apprenticeships.Infrastructure.Presentation;
    using SFA.Apprenticeships.Web.Candidate;
    using SFA.Apprenticeships.Web.Candidate.Constants;
    using SFA.Apprenticeships.Web.Candidate.Constants.ViewModels;
    using SFA.Apprenticeships.Web.Candidate.Helpers;
    using SFA.Apprenticeships.Web.Candidate.ViewModels;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.Candidate;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.Login;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.Register;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.VacancySearch;
    using SFA.Apprenticeships.Web.Common.Constants;
    using SFA.Apprenticeships.Web.Common.Framework;
    using SFA.Apprenticeships.Web.Common.Models.Common;
    using SFA.Apprenticeships.Web.Common.ViewModels.Locations;
    using SFA.Apprenticeships.Web.Common.Views.Shared.DisplayTemplates;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/TraineeshipSearch/Details.cshtml")]
    public partial class Details : System.Web.Mvc.WebViewPage<TraineeshipVacancyDetailViewModel>
    {
        public Details()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\TraineeshipSearch\Details.cshtml"
  
    ViewBag.Title = Model.Title + " - Find a traineeship";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("metatags", () => {

WriteLiteral("\r\n    <meta");

WriteLiteral(" name=\"DCSext.Days2Close\"");

WriteAttribute("content", Tuple.Create(" content=\"", 284), Tuple.Create("\"", 389)
            
            #line 10 "..\..\Views\TraineeshipSearch\Details.cshtml"
, Tuple.Create(Tuple.Create("", 294), Tuple.Create<System.Object, System.Int32>((DateTime.SpecifyKind(Model.ClosingDate, DateTimeKind.Utc).Date - DateTime.UtcNow.Date).Days
            
            #line default
            #line hidden
, 294), false)
);

WriteLiteral("/>\r\n");

});

WriteLiteral("\r\n<div itemscope");

WriteLiteral(" itemtype=\"http://schema.org/JobPosting\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"grid-wrapper\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"grid grid-2-3\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"hgroup text\"");

WriteLiteral(">\r\n                <h1");

WriteLiteral(" class=\"heading-xlarge\"");

WriteLiteral(" id=\"vacancy-title\"");

WriteLiteral(" itemprop=\"title\"");

WriteLiteral(">");

            
            #line 17 "..\..\Views\TraineeshipSearch\Details.cshtml"
                                                                          Write(HtmlExtensions.EscapeHtmlEncoding(Html, Model.Title));

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n                <p");

WriteLiteral(" class=\"subtitle\"");

WriteLiteral(" id=\"vacancy-subtitle-employer-name\"");

WriteLiteral(" itemprop=\"hiringOrganization\"");

WriteLiteral(">");

            
            #line 18 "..\..\Views\TraineeshipSearch\Details.cshtml"
                                                                                                 Write(Model.EmployerName);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"grid grid-1-3\"");

WriteLiteral(">\r\n");

            
            #line 22 "..\..\Views\TraineeshipSearch\Details.cshtml"
            
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\TraineeshipSearch\Details.cshtml"
             if (ViewBag.SearchReturnUrl != null)
            {

            
            #line default
            #line hidden
WriteLiteral("                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 987), Tuple.Create("\"", 1018)
            
            #line 24 "..\..\Views\TraineeshipSearch\Details.cshtml"
, Tuple.Create(Tuple.Create("", 994), Tuple.Create<System.Object, System.Int32>(ViewBag.SearchReturnUrl
            
            #line default
            #line hidden
, 994), false)
);

WriteLiteral(" title=\"Return to search results\"");

WriteLiteral(" class=\"page-link\"");

WriteLiteral(" id=\"lnk-return-search-results\"");

WriteLiteral(">Return to search results</a>\r\n");

            
            #line 25 "..\..\Views\TraineeshipSearch\Details.cshtml"
            }
            else
            {
                
            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\TraineeshipSearch\Details.cshtml"
           Write(Html.RouteLink("Find a traineeship", CandidateRouteNames.TraineeshipSearch, null, new { id = "lnk-find-traineeship", @class = "page-link" }));

            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\TraineeshipSearch\Details.cshtml"
                                                                                                                                                             
            }

            
            #line default
            #line hidden
WriteLiteral("            <p");

WriteLiteral(" class=\"page-link hide-nojs\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" class=\"print-trigger\"");

WriteLiteral(" href=\"\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-print\"");

WriteLiteral("></i>Print this page</a>\r\n            </p>\r\n        </div>\r\n    </div>\r\n\r\n");

            
            #line 36 "..\..\Views\TraineeshipSearch\Details.cshtml"
    
            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\TraineeshipSearch\Details.cshtml"
     if (!Model.HasError())
    {

            
            #line default
            #line hidden
WriteLiteral("        <section");

WriteLiteral(" class=\" grid-wrapper\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"grid grid-2-3\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"inner-block-padr\"");

WriteLiteral(">\r\n                    <p");

WriteAttribute("class", Tuple.Create(" class=\"", 1732), Tuple.Create("\"", 1790)
            
            #line 41 "..\..\Views\TraineeshipSearch\Details.cshtml"
, Tuple.Create(Tuple.Create("", 1740), Tuple.Create<System.Object, System.Int32>(Model.Description.GetPreserveFormattingCssClass()
            
            #line default
            #line hidden
, 1740), false)
);

WriteLiteral(">");

            
            #line 41 "..\..\Views\TraineeshipSearch\Details.cshtml"
                                                                             Write(HtmlExtensions.EscapeHtmlEncoding(Html, Model.Description));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"grid grid-1-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 45 "..\..\Views\TraineeshipSearch\Details.cshtml"
           Write(Html.Partial("_Apply", Model, new ViewDataDictionary { new KeyValuePair<string, object>("AnalyticsButtonPosition", "Top") }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </section>\r\n");

WriteLiteral("        <section");

WriteLiteral(" class=\"section-border grid-wrapper\"");

WriteLiteral(">\r\n            <h2");

WriteLiteral(" class=\"heading-large\"");

WriteLiteral(">Traineeship details</h2>\r\n            <div");

WriteLiteral(" class=\"grid grid-2-3\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"inner-block-padr\"");

WriteLiteral(">\r\n                    <p");

WriteLiteral(" id=\"vacancy-full-descrpition\"");

WriteAttribute("class", Tuple.Create(" class=\"", 2385), Tuple.Create("\"", 2447)
            
            #line 52 "..\..\Views\TraineeshipSearch\Details.cshtml"
, Tuple.Create(Tuple.Create("", 2393), Tuple.Create<System.Object, System.Int32>(Model.FullDescription.GetPreserveFormattingCssClass()
            
            #line default
            #line hidden
, 2393), false)
);

WriteLiteral(">");

            
            #line 52 "..\..\Views\TraineeshipSearch\Details.cshtml"
                                                                                                               Write(HtmlExtensions.EscapeHtmlEncoding(Html, Model.FullDescription));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                    <h3");

WriteLiteral(" class=\"heading-medium\"");

WriteLiteral(">Training to be provided</h3>\r\n                    <p");

WriteAttribute("class", Tuple.Create(" class=\"", 2617), Tuple.Create("\"", 2684)
            
            #line 54 "..\..\Views\TraineeshipSearch\Details.cshtml"
, Tuple.Create(Tuple.Create("", 2625), Tuple.Create<System.Object, System.Int32>(Model.TrainingToBeProvided.GetPreserveFormattingCssClass()
            
            #line default
            #line hidden
, 2625), false)
);

WriteLiteral(">");

            
            #line 54 "..\..\Views\TraineeshipSearch\Details.cshtml"
                                                                                      Write(HtmlExtensions.EscapeHtmlEncoding(Html, Model.TrainingToBeProvided));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"grid grid-1-3\"");

WriteLiteral(">\r\n");

            
            #line 58 "..\..\Views\TraineeshipSearch\Details.cshtml"
                
            
            #line default
            #line hidden
            
            #line 58 "..\..\Views\TraineeshipSearch\Details.cshtml"
                 if (!Model.IsEmployerAnonymous)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <h3");

WriteLiteral(" class=\"bold-small\"");

WriteLiteral(">Training provider</h3>\r\n");

WriteLiteral("                    <p>");

            
            #line 61 "..\..\Views\TraineeshipSearch\Details.cshtml"
                  Write(Model.RecruitmentAgency);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 62 "..\..\Views\TraineeshipSearch\Details.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <h3");

WriteLiteral(" class=\"bold-small\"");

WriteLiteral(">Training provider</h3>\r\n");

WriteLiteral("                    <p>");

            
            #line 66 "..\..\Views\TraineeshipSearch\Details.cshtml"
                  Write(Model.ProviderName);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 67 "..\..\Views\TraineeshipSearch\Details.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                <h3");

WriteLiteral(" class=\"bold-small\"");

WriteLiteral(">Contact</h3>\r\n                <p>");

            
            #line 71 "..\..\Views\TraineeshipSearch\Details.cshtml"
              Write(Model.Contact);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                <h3");

WriteLiteral(" class=\"bold-small\"");

WriteLiteral(">Traineeship duration</h3>\r\n                <p");

WriteLiteral(" id=\"vacancy-expected-duration\"");

WriteLiteral(">");

            
            #line 73 "..\..\Views\TraineeshipSearch\Details.cshtml"
                                              Write(string.IsNullOrWhiteSpace(Model.ExpectedDuration) ? "Not specified" : Model.ExpectedDuration);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                <h3");

WriteLiteral(" class=\"bold-small\"");

WriteLiteral(">Possible start date</h3>\r\n                <p");

WriteLiteral(" id=\"vacancy-start-date\"");

WriteLiteral(">");

            
            #line 75 "..\..\Views\TraineeshipSearch\Details.cshtml"
                                      Write(Html.DisplayFor(m => Model.StartDate));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                <h3");

WriteLiteral(" class=\"bold-small\"");

WriteLiteral(">Date posted</h3>\r\n                <p");

WriteLiteral(" id=\"vacancy-posted-date\"");

WriteLiteral(">");

            
            #line 77 "..\..\Views\TraineeshipSearch\Details.cshtml"
                                       Write(Model.PostedDate.ToFriendlyDaysAgo());

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 78 "..\..\Views\TraineeshipSearch\Details.cshtml"
                
            
            #line default
            #line hidden
            
            #line 78 "..\..\Views\TraineeshipSearch\Details.cshtml"
                 if (Model.Distance != null)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <h3");

WriteLiteral(" class=\"bold-small\"");

WriteLiteral(">Distance</h3>\r\n");

WriteLiteral("                    <p");

WriteLiteral(" id=\"vacancy-distance\"");

WriteLiteral(">");

            
            #line 81 "..\..\Views\TraineeshipSearch\Details.cshtml"
                                        Write(Model.Distance);

            
            #line default
            #line hidden
WriteLiteral(" miles</p>\r\n");

            
            #line 82 "..\..\Views\TraineeshipSearch\Details.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <h3");

WriteLiteral(" class=\"bold-small\"");

WriteLiteral(">Reference number</h3>\r\n                <p");

WriteLiteral(" id=\"vacancy-reference-id\"");

WriteLiteral(">");

            
            #line 84 "..\..\Views\TraineeshipSearch\Details.cshtml"
                                        Write(Model.VacancyReference);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 85 "..\..\Views\TraineeshipSearch\Details.cshtml"
                
            
            #line default
            #line hidden
            
            #line 85 "..\..\Views\TraineeshipSearch\Details.cshtml"
                 if (Model.VacancyLocationType != ApprenticeshipLocationType.National)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <h3");

WriteLiteral(" class=\"bold-small\"");

WriteLiteral(">Positions</h3>\r\n");

WriteLiteral("                    <p");

WriteLiteral(" id=\"number-of-positions\"");

WriteLiteral(">");

            
            #line 88 "..\..\Views\TraineeshipSearch\Details.cshtml"
                                           Write(Model.NumberOfPositions);

            
            #line default
            #line hidden
WriteLiteral(" available</p>\r\n");

            
            #line 89 "..\..\Views\TraineeshipSearch\Details.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </section>\r\n");

WriteLiteral("        <section");

WriteLiteral(" class=\"section-border grid-wrapper\"");

WriteLiteral(" id=\"vacancy-info\"");

WriteLiteral(">\r\n            <h2");

WriteLiteral(" class=\"heading-large\"");

WriteLiteral(">Employer</h2>\r\n            <div");

WriteLiteral(" class=\"grid-wrapper\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"grid grid-1-2\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"inner-block-padr\"");

WriteLiteral(">\r\n                        <p");

WriteLiteral(" id=\"vacancy-employer-name\"");

WriteAttribute("class", Tuple.Create(" class=\"", 4818), Tuple.Create("\"", 4888)
            
            #line 98 "..\..\Views\TraineeshipSearch\Details.cshtml"
, Tuple.Create(Tuple.Create("", 4826), Tuple.Create<System.Object, System.Int32>(Model.IsWellFormedEmployerWebsiteUrl ? "no-btm-margin" : ""
            
            #line default
            #line hidden
, 4826), false)
);

WriteLiteral(">");

            
            #line 98 "..\..\Views\TraineeshipSearch\Details.cshtml"
                                                                                                                        Write(Model.EmployerName);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 99 "..\..\Views\TraineeshipSearch\Details.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 99 "..\..\Views\TraineeshipSearch\Details.cshtml"
                         if (Model.IsEmployerAnonymous)
                        {
                            if (Model.VacancyLocationType != ApprenticeshipLocationType.National)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <div itemscope");

WriteLiteral(" itemtype=\"http://schema.org/PostalAddress\"");

WriteLiteral(">\r\n                                    <h3");

WriteLiteral(" class=\"bold-small\"");

WriteLiteral(">Address</h3>\r\n                                    <div");

WriteLiteral(" itemprop=\"address\"");

WriteLiteral(">\r\n                                        <p");

WriteLiteral(" class=\"small-btm-margin\"");

WriteLiteral(" itemprop=\"addressLocality\"");

WriteLiteral(">");

            
            #line 106 "..\..\Views\TraineeshipSearch\Details.cshtml"
                                                                                          Write(Model.VacancyAddress.Town);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                    </div>\r\n                               " +
" </div>\r\n");

            
            #line 109 "..\..\Views\TraineeshipSearch\Details.cshtml"
                            }
                        }
                        else
                        {
                            if (Model.IsWellFormedEmployerWebsiteUrl)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <p><a");

WriteLiteral(" itemprop=\"url\"");

WriteAttribute("href", Tuple.Create(" href=\"", 5836), Tuple.Create("\"", 5865)
            
            #line 115 "..\..\Views\TraineeshipSearch\Details.cshtml"
, Tuple.Create(Tuple.Create("", 5843), Tuple.Create<System.Object, System.Int32>(Model.EmployerWebsite
            
            #line default
            #line hidden
, 5843), false)
);

WriteLiteral(" id=\"vacancy-employer-website\"");

WriteLiteral(" target=\"_blank\"");

WriteAttribute("title", Tuple.Create(" title=\"", 5912), Tuple.Create("\"", 5947)
            
            #line 115 "..\..\Views\TraineeshipSearch\Details.cshtml"
                                                        , Tuple.Create(Tuple.Create("", 5920), Tuple.Create<System.Object, System.Int32>(Model.EmployerName
            
            #line default
            #line hidden
, 5920), false)
, Tuple.Create(Tuple.Create(" ", 5939), Tuple.Create("Website", 5940), true)
);

WriteLiteral(" rel=\"external\"");

WriteLiteral(">");

            
            #line 115 "..\..\Views\TraineeshipSearch\Details.cshtml"
                                                                                                                                                                               Write(Model.EmployerWebsite);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                </p>\r\n");

            
            #line 117 "..\..\Views\TraineeshipSearch\Details.cshtml"
                            }
                            else
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <p>");

            
            #line 120 "..\..\Views\TraineeshipSearch\Details.cshtml"
                              Write(Model.EmployerWebsite);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 121 "..\..\Views\TraineeshipSearch\Details.cshtml"
                            }
                            if (Model.VacancyLocationType != ApprenticeshipLocationType.National)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <div itemscope");

WriteLiteral(" itemtype=\"http://schema.org/PostalAddress\"");

WriteLiteral(">\r\n                                    <h3");

WriteLiteral(" class=\"bold-small\"");

WriteLiteral(">Address</h3>\r\n                                    <div");

WriteLiteral(" itemprop=\"address\"");

WriteLiteral(">\r\n                                        <p");

WriteLiteral(" class=\"small-btm-margin\"");

WriteLiteral(" itemprop=\"streetAddress\"");

WriteLiteral(">");

            
            #line 127 "..\..\Views\TraineeshipSearch\Details.cshtml"
                                                                                        Write(Model.VacancyAddress.AddressLine1);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                        <p");

WriteLiteral(" class=\"small-btm-margin\"");

WriteLiteral(" itemprop=\"streetAddress\"");

WriteLiteral(">");

            
            #line 128 "..\..\Views\TraineeshipSearch\Details.cshtml"
                                                                                        Write(Model.VacancyAddress.AddressLine2);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                        <p");

WriteLiteral(" class=\"small-btm-margin\"");

WriteLiteral(" itemprop=\"streetAddress\"");

WriteLiteral(">");

            
            #line 129 "..\..\Views\TraineeshipSearch\Details.cshtml"
                                                                                        Write(Model.VacancyAddress.AddressLine3);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                        <p");

WriteLiteral(" class=\"small-btm-margin\"");

WriteLiteral(" itemprop=\"addressLocality\"");

WriteLiteral(">");

            
            #line 130 "..\..\Views\TraineeshipSearch\Details.cshtml"
                                                                                          Write(Model.VacancyAddress.Town);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                        <p");

WriteLiteral(" class=\"small-btm-margin\"");

WriteLiteral(" itemprop=\"addressRegion\"");

WriteLiteral(">");

            
            #line 131 "..\..\Views\TraineeshipSearch\Details.cshtml"
                                                                                        Write(Model.VacancyAddress.County);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                        <p");

WriteLiteral(" class=\"\"");

WriteLiteral(" itemprop=\"postalCode\"");

WriteLiteral(">");

            
            #line 132 "..\..\Views\TraineeshipSearch\Details.cshtml"
                                                                     Write(Model.VacancyAddress.Postcode);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                    </div>\r\n                               " +
" </div>\r\n");

            
            #line 135 "..\..\Views\TraineeshipSearch\Details.cshtml"
                            }
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                </div>\r\n");

            
            #line 139 "..\..\Views\TraineeshipSearch\Details.cshtml"
                
            
            #line default
            #line hidden
            
            #line 139 "..\..\Views\TraineeshipSearch\Details.cshtml"
                 if (Model.VacancyLocationType != ApprenticeshipLocationType.National)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"grid grid-1-2 hide-print\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"ad-details__map\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"map-overlay\"");

WriteLiteral(" onclick=\"style.pointerEvents = \'none\'\"");

WriteLiteral("></div>\r\n");

            
            #line 144 "..\..\Views\TraineeshipSearch\Details.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 144 "..\..\Views\TraineeshipSearch\Details.cshtml"
                             if (Model.IsEmployerAnonymous)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <div");

WriteLiteral(" id=\"anonymous-map\"");

WriteLiteral(">\r\n                                    <iframe");

WriteLiteral(" width=\"700\"");

WriteLiteral(" height=\"250\"");

WriteLiteral(" title=\"Map of location\"");

WriteLiteral(" style=\"border: 0\"");

WriteAttribute("src", Tuple.Create(" src=\"", 8116), Tuple.Create("\"", 8310)
, Tuple.Create(Tuple.Create("", 8122), Tuple.Create("https://www.google.com/maps/embed/v1/view?center=", 8122), true)
            
            #line 147 "..\..\Views\TraineeshipSearch\Details.cshtml"
                                                                                     , Tuple.Create(Tuple.Create("", 8171), Tuple.Create<System.Object, System.Int32>(Model.VacancyAddress.GeoPoint.Latitude
            
            #line default
            #line hidden
, 8171), false)
, Tuple.Create(Tuple.Create("", 8210), Tuple.Create(",", 8210), true)
            
            #line 147 "..\..\Views\TraineeshipSearch\Details.cshtml"
                                                                                                                             , Tuple.Create(Tuple.Create("", 8211), Tuple.Create<System.Object, System.Int32>(Model.VacancyAddress.GeoPoint.Longitude
            
            #line default
            #line hidden
, 8211), false)
, Tuple.Create(Tuple.Create("", 8251), Tuple.Create("&amp;zoom=9&amp;key=AIzaSyCusA_0x4bJEjU-_gLOFiXMSBXKZYtvHz8", 8251), true)
);

WriteLiteral("></iframe>\r\n                                </div>\r\n");

            
            #line 149 "..\..\Views\TraineeshipSearch\Details.cshtml"
                            }
                            else
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <iframe");

WriteLiteral(" width=\"700\"");

WriteLiteral(" height=\"250\"");

WriteLiteral(" frameborder=\"0\"");

WriteLiteral(" style=\"border: 0\"");

WriteAttribute("src", Tuple.Create(" src=\"", 8557), Tuple.Create("\"", 8712)
, Tuple.Create(Tuple.Create("", 8563), Tuple.Create("https://www.google.com/maps/embed/v1/place?q=", 8563), true)
            
            #line 152 "..\..\Views\TraineeshipSearch\Details.cshtml"
                                                                     , Tuple.Create(Tuple.Create("", 8608), Tuple.Create<System.Object, System.Int32>(Html.Raw(Model.VacancyAddress.Postcode)
            
            #line default
            #line hidden
, 8608), false)
, Tuple.Create(Tuple.Create("", 8648), Tuple.Create(",+United+Kingdom&amp;key=AIzaSyCusA_0x4bJEjU-_gLOFiXMSBXKZYtvHz8", 8648), true)
);

WriteLiteral("></iframe>\r\n");

            
            #line 153 "..\..\Views\TraineeshipSearch\Details.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <p");

WriteLiteral(" class=\"nojs-notice\"");

WriteLiteral(">You must have JavaScript enabled to view a map of the location</p>\r\n            " +
"            </div>\r\n                    </div>\r\n");

            
            #line 158 "..\..\Views\TraineeshipSearch\Details.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 159 "..\..\Views\TraineeshipSearch\Details.cshtml"
                 if (!string.IsNullOrWhiteSpace(Model.AdditionalLocationInformation))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"grid text\"");

WriteLiteral(">\r\n                        <p></p>\r\n                        <h3");

WriteLiteral(" class=\"bold-small\"");

WriteLiteral(">\r\n                            Additional location information\r\n                 " +
"       </h3>\r\n                        <p>");

            
            #line 166 "..\..\Views\TraineeshipSearch\Details.cshtml"
                      Write(HtmlExtensions.EscapeHtmlEncoding(Html, Model.AdditionalLocationInformation));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                    </div>\r\n");

            
            #line 168 "..\..\Views\TraineeshipSearch\Details.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </section>\r\n");

WriteLiteral("        <section");

WriteLiteral(" class=\"section-border grid-wrapper\"");

WriteLiteral(" id=\"course-info\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"text\"");

WriteLiteral(">\r\n                <h2");

WriteLiteral(" class=\"heading-large\"");

WriteLiteral(">Desired skills and what this will lead to</h2>\r\n                <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral(">Desired skills and qualities</h3>\r\n                <p");

WriteAttribute("class", Tuple.Create(" class=\"", 9767), Tuple.Create("\"", 9828)
            
            #line 175 "..\..\Views\TraineeshipSearch\Details.cshtml"
, Tuple.Create(Tuple.Create("", 9775), Tuple.Create<System.Object, System.Int32>(Model.SkillsRequired.GetPreserveFormattingCssClass()
            
            #line default
            #line hidden
, 9775), false)
);

WriteLiteral(">");

            
            #line 175 "..\..\Views\TraineeshipSearch\Details.cshtml"
                                                                            Write(HtmlExtensions.EscapeHtmlEncoding(Html, Model.SkillsRequired));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                <p");

WriteAttribute("class", Tuple.Create(" class=\"", 9916), Tuple.Create("\"", 9980)
            
            #line 176 "..\..\Views\TraineeshipSearch\Details.cshtml"
, Tuple.Create(Tuple.Create("", 9924), Tuple.Create<System.Object, System.Int32>(Model.PersonalQualities.GetPreserveFormattingCssClass()
            
            #line default
            #line hidden
, 9924), false)
);

WriteLiteral(">");

            
            #line 176 "..\..\Views\TraineeshipSearch\Details.cshtml"
                                                                               Write(HtmlExtensions.EscapeHtmlEncoding(Html, Model.PersonalQualities));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n\r\n");

            
            #line 178 "..\..\Views\TraineeshipSearch\Details.cshtml"
                
            
            #line default
            #line hidden
            
            #line 178 "..\..\Views\TraineeshipSearch\Details.cshtml"
                 if (!string.IsNullOrWhiteSpace(Model.FutureProspects))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <h3");

WriteLiteral(" class=\"heading-small\"");

WriteLiteral(">What this will lead to</h3>\r\n");

WriteLiteral("                    <p");

WriteLiteral(" id=\"vacancy-future-prospects\"");

WriteAttribute("class", Tuple.Create(" class=\"", 10274), Tuple.Create("\"", 10336)
            
            #line 181 "..\..\Views\TraineeshipSearch\Details.cshtml"
, Tuple.Create(Tuple.Create("", 10282), Tuple.Create<System.Object, System.Int32>(Model.FutureProspects.GetPreserveFormattingCssClass()
            
            #line default
            #line hidden
, 10282), false)
);

WriteLiteral(">");

            
            #line 181 "..\..\Views\TraineeshipSearch\Details.cshtml"
                                                                                                               Write(HtmlExtensions.EscapeHtmlEncoding(Html, Model.FutureProspects));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 182 "..\..\Views\TraineeshipSearch\Details.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </section>\r\n");

            
            #line 185 "..\..\Views\TraineeshipSearch\Details.cshtml"

        if (!string.IsNullOrWhiteSpace(Model.OtherInformation))
        {

            
            #line default
            #line hidden
WriteLiteral("            <section");

WriteLiteral(" class=\"grid-wrapper\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"text\"");

WriteLiteral(">\r\n                    <h2");

WriteLiteral(" class=\"heading-large\"");

WriteLiteral(">Other information</h2>\r\n                    <p");

WriteLiteral(" id=\"vacany-other-information\"");

WriteAttribute("class", Tuple.Create(" class=\"", 10746), Tuple.Create("\"", 10809)
            
            #line 191 "..\..\Views\TraineeshipSearch\Details.cshtml"
, Tuple.Create(Tuple.Create("", 10754), Tuple.Create<System.Object, System.Int32>(Model.OtherInformation.GetPreserveFormattingCssClass()
            
            #line default
            #line hidden
, 10754), false)
);

WriteLiteral(">");

            
            #line 191 "..\..\Views\TraineeshipSearch\Details.cshtml"
                                                                                                                Write(HtmlExtensions.EscapeHtmlEncoding(Html, Model.OtherInformation));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                </div>\r\n            </section>\r\n");

            
            #line 194 "..\..\Views\TraineeshipSearch\Details.cshtml"
        }
    }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
